package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BbsJob struct {

	/*Diego - Descr: Addresses pointing to the ETCD cluster Default: [etcd.service.cf.internal]
*/
	Diego *Diego `yaml:"diego,omitempty"`

}