package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Bbs - Descr: Addresses pointing to the ETCD cluster Default: [etcd.service.cf.internal]
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

}