package consul_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConsulAgentJob struct {

	/*Consul - Descr: PEM-encoded CA certificate Default: <nil>
*/
	Consul *Consul `yaml:"consul,omitempty"`

}