package streaming_mysql_backup_tool 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StreamingMysqlBackupToolJob struct {

	/*MysqlBackup - Descr: Command which is executed in order to take a backup Default: <nil>
*/
	MysqlBackup *MysqlBackup `yaml:"mysql-backup,omitempty"`

}