package route_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RouteEmitterJob struct {

	/*Diego - Descr: Username for server authentication. Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}