package route_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RouteEmitter struct {

	/*LogLevel - Descr: Log level Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*DropsondePort - Descr: local metron agent's port Default: 3457
*/
	DropsondePort interface{} `yaml:"dropsonde_port,omitempty"`

	/*Bbs - Descr: Address to the BBS Server Default: bbs.service.cf.internal:8889
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*SyncIntervalInSeconds - Descr: Interval to sync routes to the router in seconds. Default: 60
*/
	SyncIntervalInSeconds interface{} `yaml:"sync_interval_in_seconds,omitempty"`

	/*Nats - Descr: Username for server authentication. Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*DebugAddr - Descr: address at which to serve debug info Default: 0.0.0.0:17009
*/
	DebugAddr interface{} `yaml:"debug_addr,omitempty"`

}