package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Authn struct {

	/*SecurityKeystoreFilepath - Descr: path on remote system for your keystore Default: /var/vcap/store
*/
	SecurityKeystoreFilepath interface{} `yaml:"security_keystore_filepath,omitempty"`

	/*SecurityPublickeyPass - Descr: password for the given key Default: <nil>
*/
	SecurityPublickeyPass interface{} `yaml:"security_publickey_pass,omitempty"`

	/*Enabled - Descr: do we want to enable authentication for this deployment Default: false
*/
	Enabled interface{} `yaml:"enabled,omitempty"`

	/*KeystoreBits - Descr: keystore file bits, base64 encoded Default: <nil>
*/
	KeystoreBits interface{} `yaml:"keystore_bits,omitempty"`

	/*SecurityClientAuthenticator - Descr: what should the value of the gemfire property for security-client-authenticator be Default: DummyAuthenticator.create
*/
	SecurityClientAuthenticator interface{} `yaml:"security_client_authenticator,omitempty"`

}