package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ClusterTopology struct {

	/*NumberOfLocators - Descr: Number of locators per cluster Default: 0
*/
	NumberOfLocators interface{} `yaml:"number_of_locators,omitempty"`

	/*NumberOfServers - Descr: Number of cache servers per cluster Default: 0
*/
	NumberOfServers interface{} `yaml:"number_of_servers,omitempty"`

}