package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DevRestApi struct {

	/*Port - Descr: the port your dev rest api will listen on Default: 7070
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Active - Descr: activate the dev rest api on your gemfire server nodes Default: false
*/
	Active interface{} `yaml:"active,omitempty"`

}