package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Gemfire struct {

	/*Locator - Descr: List of GemFire Locator addresses of the form X.X.X.X Default: <nil>
*/
	Locator *Locator `yaml:"locator,omitempty"`

	/*Server - Descr: RAM allocated to the VM Default: <nil>
*/
	Server *Server `yaml:"server,omitempty"`

	/*ClusterTopology - Descr: Number of locators per cluster Default: 0
*/
	ClusterTopology *ClusterTopology `yaml:"cluster_topology,omitempty"`

	/*Authn - Descr: password for the given key Default: <nil>
*/
	Authn *Authn `yaml:"authn,omitempty"`

}