package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Gemfire struct {

	/*Locator - Descr: Port the Locator is listening on Default: <nil>
*/
	Locator *Locator `yaml:"locator,omitempty"`

	/*Authn - Descr: what should the value of the gemfire property for security-client-authenticator be Default: DummyAuthenticator.create
*/
	Authn *Authn `yaml:"authn,omitempty"`

	/*ClusterTopology - Descr: Number of locators per cluster Default: 0
*/
	ClusterTopology *ClusterTopology `yaml:"cluster_topology,omitempty"`

	/*Server - Descr: activate the dev rest api on your gemfire server nodes Default: false
*/
	Server *Server `yaml:"server,omitempty"`

}