package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Locator struct {

	/*Addresses - Descr: List of GemFire Locator addresses of the form X.X.X.X Default: <nil>
*/
	Addresses interface{} `yaml:"addresses,omitempty"`

	/*Port - Descr: Port the Locator is listening on Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

}