package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ServerJob struct {

	/*Gemfire - Descr: password for the given key Default: <nil>
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

}