package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ServerJob struct {

	/*Gemfire - Descr: what should the value of the gemfire property for security-client-authenticator be Default: DummyAuthenticator.create
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

}