package server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Server struct {

	/*Port - Descr: Port the Server will listen on Default: 55001
*/
	Port interface{} `yaml:"port,omitempty"`

	/*RestPort - Descr: Port for the REST endpoint for administration Default: 8080
*/
	RestPort interface{} `yaml:"rest_port,omitempty"`

	/*VmMemory - Descr: RAM allocated to the VM Default: <nil>
*/
	VmMemory interface{} `yaml:"vm_memory,omitempty"`

}