package debian_nfs_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DebianNfsServerJob struct {

	/*NfsServer - Descr: An array of Hosts, Domains, Wildcard Domains, CIDR Networks and/or IPs from which /var/vcap/store is accessible Default: <nil>
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

}