package debian_nfs_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DebianNfsServerJob struct {

	/*NfsServer - Descr: Domain name for NFS idmapd Default: localdomain
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

}