package garden 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GardenJob struct {

	/*Garden - Descr: list of comma-separated hosts for which the http and https proxies will be skipped Default: <nil>
*/
	Garden *Garden `yaml:"garden,omitempty"`

}