package garden 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GardenJob struct {

	/*Garden - Descr: Maximum number of containers that garden will have running at the same time. It is not recommended to set this larger than 250. Default: 250
*/
	Garden *Garden `yaml:"garden,omitempty"`

}