package ssh_proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SshProxyJob struct {

	/*Diego - Descr: address at which to serve debug info Default: 0.0.0.0:17016
*/
	Diego *Diego `yaml:"diego,omitempty"`

}