package dea_next 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*InternalApiUser - Descr: User name to access internal endpoints Default: internal_user
*/
	InternalApiUser interface{} `yaml:"internal_api_user,omitempty"`

	/*InternalApiPassword - Descr: Password to access internal endpoints Default: <nil>
*/
	InternalApiPassword interface{} `yaml:"internal_api_password,omitempty"`

	/*ExternalPort - Descr: External Cloud Controller port Default: 9022
*/
	ExternalPort interface{} `yaml:"external_port,omitempty"`

}