package send_email 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AdminClient struct {

	/*Username - Descr: Username of the UAA admin client used to (idempotently) create the notifications client Default: admin
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Secret - Descr: Secret of the UAA admin client used to (idempotently) create the notifications client Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}