package send_email 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Client struct {

	/*Username - Descr: Username of the UAA client used to send mysql monitoring notifications Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Secret - Descr: Secret of the UAA client used to send mysql monitoring notifications Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}