package send_email 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MysqlMonitoring struct {

	/*Client - Descr: Secret of the UAA client used to send mysql monitoring notifications Default: <nil>
*/
	Client *Client `yaml:"client,omitempty"`

	/*RecipientEmail - Descr: The email address to send mysql monitoring notifications to Default: 
*/
	RecipientEmail interface{} `yaml:"recipient_email,omitempty"`

	/*AdminClient - Descr: Secret of the UAA admin client used to (idempotently) create the notifications client Default: <nil>
*/
	AdminClient *AdminClient `yaml:"admin_client,omitempty"`

}