package send_email 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SendEmailJob struct {

	/*Domain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Ssl - Descr: specifies that the job is allowed to skip ssl cert verification Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*MysqlMonitoring - Descr: The email address to send mysql monitoring notifications to Default: 
*/
	MysqlMonitoring *MysqlMonitoring `yaml:"mysql-monitoring,omitempty"`

}