package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerDeregistrarJob struct {

	/*Broker - Descr: Name of the service broker Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Cf - Descr: Full URL of Cloud Foundry API Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

}