package destroy_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SpringCloudBroker struct {

	/*Cf - Descr: Username of the CF admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*Worker - Descr: Worker Client Secret Default: <nil>
*/
	Worker *Worker `yaml:"worker,omitempty"`

	/*Uaa - Descr: Client ID of the UAA admin client Default: <nil>
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Broker - Descr: Org that hosts the Service Broker Default: system
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Instances - Descr: Username with access to instances space Default: <nil>
*/
	Instances *Instances `yaml:"instances,omitempty"`

	/*ProductName - Descr: Product Name Default: p-spring-cloud-services
*/
	ProductName interface{} `yaml:"product_name,omitempty"`

	/*AppUri - Descr: App URI Default: spring-cloud-broker
*/
	AppUri interface{} `yaml:"app_uri,omitempty"`

	/*AppName - Descr: App Name Default: spring-cloud-broker
*/
	AppName interface{} `yaml:"app_name,omitempty"`

}