package destroy_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Worker struct {

	/*ClientSecret - Descr: Worker Client Secret Default: <nil>
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

	/*ClientId - Descr: Worker Client ID Default: p-spring-cloud-services-worker
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

}