package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ProxyJob struct {

	/*CfMysql - Descr: Port for the proxy to listen on Default: 3306
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*Nats - Descr: Username to register a route via NATS Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*SyslogAggregator - Descr: IP address for syslog aggregator Default: <nil>
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

}