package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Proxy struct {

	/*HealthcheckTimeoutMillis - Descr: Timeout (milliseconds) before assuming a backend is unhealthy Default: 5000
*/
	HealthcheckTimeoutMillis interface{} `yaml:"healthcheck_timeout_millis,omitempty"`

	/*ApiPort - Descr: Port for the proxy API to listen on Default: 8080
*/
	ApiPort interface{} `yaml:"api_port,omitempty"`

	/*ApiUsername - Descr: Username for Basic Auth used to secure API Default: <nil>
*/
	ApiUsername interface{} `yaml:"api_username,omitempty"`

	/*ProxyIps - Descr: Optional, list of IP addresses for all proxy jobs Default: <nil>
*/
	ProxyIps interface{} `yaml:"proxy_ips,omitempty"`

	/*ConsulEnabled - Descr: Enable locking and discovery of switchboard through consul Default: false
*/
	ConsulEnabled interface{} `yaml:"consul_enabled,omitempty"`

	/*ProfilingEnabled - Descr: When set to true, the switchboard will listen on port 6060 and enable profiling of the process Default: false
*/
	ProfilingEnabled interface{} `yaml:"profiling_enabled,omitempty"`

	/*HealthPort - Descr: Port for checking the health of the proxy process Default: 1936
*/
	HealthPort interface{} `yaml:"health_port,omitempty"`

	/*ConsulServiceName - Descr: Switchboard will register with consul using this name Default: mysql
*/
	ConsulServiceName interface{} `yaml:"consul_service_name,omitempty"`

	/*Port - Descr: Port for the proxy to listen on Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

	/*ArbitratorIp - Descr: Optional, list of IP addresses for the arbitrator nodes of the MySQL cluster Default: <nil>
*/
	ArbitratorIp interface{} `yaml:"arbitrator_ip,omitempty"`

	/*MaxOpenFiles - Descr: Configure this number to be twice as large as mysql.max_connections Default: 3000
*/
	MaxOpenFiles interface{} `yaml:"max_open_files,omitempty"`

	/*ApiForceHttps - Descr: Redirect all HTTP requests to the API to HTTPS Default: true
*/
	ApiForceHttps interface{} `yaml:"api_force_https,omitempty"`

	/*ApiPassword - Descr: Password for Basic Auth used to secure API Default: <nil>
*/
	ApiPassword interface{} `yaml:"api_password,omitempty"`

}