package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Clients struct {

	/*Doppler - Descr: DEPRECATED in favor of loggregator.uaa.client_secret. Default: 
*/
	Doppler *ClientsDoppler `yaml:"doppler,omitempty"`

}