package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ClientsDoppler struct {

	/*Secret - Descr: DEPRECATED in favor of loggregator.uaa.client_secret. Default: 
*/
	Secret interface{} `yaml:"secret,omitempty"`

}