package loggregator_trafficcontroller 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type LoggregatorTrafficcontrollerJob struct {

	/*Login - Descr: Protocol to use to connect to UAA (used in case uaa.url is not set) Default: https
*/
	Login *Login `yaml:"login,omitempty"`

	/*Loggregator - Descr: PEM-encoded CA certificate Default: 
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*TrafficController - Descr: Size (KB) of shell's locked memory limit. Set to 'kernel' to use the kernel's default. Non-numeric values other than 'kernel', 'soft', 'hard', and 'unlimited' will result in an error. Default: unlimited
*/
	TrafficController *TrafficController `yaml:"traffic_controller,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Uaa - Descr: DEPRECATED in favor of loggregator.uaa.client_secret. Default: 
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Doppler - Descr: Port for outgoing doppler messages Default: 8081
*/
	Doppler *Doppler `yaml:"doppler,omitempty"`

	/*MetronEndpoint - Descr: The port used to emit dropsonde messages to the Metron agent Default: 3457
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*SystemDomain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*Cc - Descr: API URI of cloud controller Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

}