package dea_logging_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DeaLoggingAgentJob struct {

	/*MetronEndpoint - Descr: The port used to emit dropsonde messages to the Metron agent Default: 3457
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*DeaLoggingAgent - Descr: boolean value to turn on verbose mode Default: false
*/
	DeaLoggingAgent *DeaLoggingAgent `yaml:"dea_logging_agent,omitempty"`

}