package replication_canary

/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
 */
type ReplicationCanaryJob struct {

	/*Domain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
	 */
	Domain interface{} `yaml:"domain,omitempty"`

	/*MysqlMonitoring - Descr: The number of switchboard proxies Default: <nil>
	 */
	MysqlMonitoring *MysqlMonitoring `yaml:"mysql-monitoring,omitempty"`

	/*SyslogAggregator - Descr: Define whether forwarders should also send non-mysql syslog activity to the aggregator. Default: false
	 */
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`
}
