package flannel 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Apiserver struct {

	/*Ip - Descr: ip of api server Default: <nil>
*/
	Ip interface{} `yaml:"ip,omitempty"`

}