package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AuctioneerJob struct {

	/*Diego - Descr: Log level Default: info
*/
	Diego *Diego `yaml:"diego,omitempty"`

}