package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AuctioneerJob struct {

	/*Diego - Descr: PEM-encoded client key Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}