package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Auctioneer - Descr: PEM-encoded client key Default: <nil>
*/
	Auctioneer *Auctioneer `yaml:"auctioneer,omitempty"`

}