package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerRegistrarJob struct {

	/*Broker - Descr: Basic plans object for registering Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Cf - Descr: Skip SSL validation when connecting to Cloud Foundry API Default: false
*/
	Cf *Cf `yaml:"cf,omitempty"`

}