package groundcrew 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GroundcrewJob struct {

	/*HttpProxyUrl - Descr: Proxy to use for outgoing http requests from containers.
 Default: <nil>
*/
	HttpProxyUrl interface{} `yaml:"http_proxy_url,omitempty"`

	/*HttpsProxyUrl - Descr: Proxy to use for outgoing https requests from containers.
 Default: <nil>
*/
	HttpsProxyUrl interface{} `yaml:"https_proxy_url,omitempty"`

	/*AdditionalResourceTypes - Descr: Additional resource types supported by the workers in `[{type: string, image: string}]` format.
 Default: []
*/
	AdditionalResourceTypes interface{} `yaml:"additional_resource_types,omitempty"`

	/*Tsa - Descr: IP or DNS address of the TSA server to register with.

If not specified, the `tsa` link is used.
 Default: <nil>
*/
	Tsa *Tsa `yaml:"tsa,omitempty"`

	/*Tags - Descr: An array of tags to advertise for each worker.
 Default: []
*/
	Tags interface{} `yaml:"tags,omitempty"`

	/*Yeller - Descr: Environment name you wish to group errors under in yeller.
 Default: 
*/
	Yeller *Yeller `yaml:"yeller,omitempty"`

	/*Garden - Descr: Garden server connection address to advertise directly to the TSA.

If not specified, either the `garden` link is used, or
the instance's address is advertised if the link is not
found.
 Default: <nil>
*/
	Garden *Garden `yaml:"garden,omitempty"`

	/*NoProxy - Descr: A list domains and IPs with optional port for which the proxy should be bypassed, e.g. [localhost, 127.0.0.1, example.com, domain.com:8080]
 Default: []
*/
	NoProxy interface{} `yaml:"no_proxy,omitempty"`

	/*Baggageclaim - Descr: Baggageclaim server URL to advertise directly to the
TSA.

If not specified, either the `baggageclaim` link is
used.
 Default: <nil>
*/
	Baggageclaim *Baggageclaim `yaml:"baggageclaim,omitempty"`

	/*Platform - Descr: Platform to advertise for each worker.
 Default: linux
*/
	Platform interface{} `yaml:"platform,omitempty"`

}