package rabbitmq_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Administrators struct {

	/*Broker - Descr: RabbitMQ admin username for broker Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Management - Descr: RabbitMQ admin username for operator Default: <nil>
*/
	Management *Management `yaml:"management,omitempty"`

}