package rabbitmq_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Management struct {

	/*Password - Descr: RabbitMQ admin password for operator Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Username - Descr: RabbitMQ admin username for operator Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

}