package rabbitmq_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RabbitmqServerJob struct {

	/*RabbitmqServer - Descr: SSL security options (currently only 'enable_tls1_0') Default: []
*/
	RabbitmqServer *RabbitmqServer `yaml:"rabbitmq-server,omitempty"`

	/*SyslogAggregator - Descr: Syslog drain port Default: <nil>
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

}