package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagerJob struct {

	/*Diego - Descr: URL for staging task callbacks Default: http://stager.service.cf.internal:8888
*/
	Diego *Diego `yaml:"diego,omitempty"`

}