package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagerJob struct {

	/*Diego - Descr: External port to access the Cloud Controller Default: 9022
*/
	Diego *Diego `yaml:"diego,omitempty"`

}