package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagerJob struct {

	/*Diego - Descr: Address to the BBS Server Default: bbs.service.cf.internal:8889
*/
	Diego *Diego `yaml:"diego,omitempty"`

}