package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NatsJob struct {

	/*Nats - Descr: Enable debug logging output. Default: false
*/
	Nats *Nats `yaml:"nats,omitempty"`

}