package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NatsJob struct {

	/*Nats - Descr: After accepting a connection, wait up to this many seconds for credentials. Default: 15
*/
	Nats *Nats `yaml:"nats,omitempty"`

}