package rejoin_unsafe 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*GaleraHealthcheck - Descr: Port used by sidecar process to listen on Default: 9200
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

}