package rejoin_unsafe 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RejoinUnsafeJob struct {

	/*ClusterIps - Descr: IP addresses of all MySQL nodes Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*CfMysql - Descr: Port used by sidecar process to listen on Default: 9200
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}