package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaJob struct {

	/*Uaadb - Descr: The list of databases used in UAA database including tag/name Default: <nil>
*/
	Uaadb *Uaadb `yaml:"uaadb,omitempty"`

	/*Login - Descr: URL for configuring a custom home page Default: <nil>
*/
	Login *Login `yaml:"login,omitempty"`

	/*Env - Descr: The http_proxy across the VMs used for all requests over https Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Uaa - Descr: Number of allowed failures before account is locked Default: 5
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

}