package rabbitmq_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Logging struct {

	/*PrintStackTraces - Descr: Should boot exception handlers print full stack traces? Default: false
*/
	PrintStackTraces interface{} `yaml:"print_stack_traces,omitempty"`

	/*Level - Descr: Logging level Default: info
*/
	Level interface{} `yaml:"level,omitempty"`

}