package rabbitmq_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Port - Descr: Port that NATS listens on Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Machines - Descr: Hostname/IP of NATS Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*Username - Descr: The user to use when authenticating with NATS Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Password - Descr: The password to use when authenticating with NATS Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}