package rabbitmq_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type OperatorSetPolicy struct {

	/*PolicyName - Descr: Operator policy name Default: operator_set_policy
*/
	PolicyName interface{} `yaml:"policy_name,omitempty"`

	/*PolicyPriority - Descr: Operator policy priority Default: 50
*/
	PolicyPriority interface{} `yaml:"policy_priority,omitempty"`

	/*PolicyDefinition - Descr: Operator policy definition Default: <nil>
*/
	PolicyDefinition interface{} `yaml:"policy_definition,omitempty"`

	/*Enabled - Descr: Enable policy set by the operator Default: false
*/
	Enabled interface{} `yaml:"enabled,omitempty"`

}