package rabbitmq_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RabbitmqBroker struct {

	/*Logging - Descr: Logging level Default: info
*/
	Logging *Logging `yaml:"logging,omitempty"`

	/*Rabbitmq - Descr: The username used to access an admin account of the Rabbit servers Default: <nil>
*/
	Rabbitmq *Rabbitmq `yaml:"rabbitmq,omitempty"`

	/*Service - Descr: Service offering description Default: RabbitMQ is a robust and scalable high-performance multi-protocol messaging broker.
*/
	Service *Service `yaml:"service,omitempty"`

	/*Ip - Descr: Broker IP Default: <nil>
*/
	Ip interface{} `yaml:"ip,omitempty"`

	/*RegistrationInterval - Descr: How often the registrar should send messages to the router Default: 20s
*/
	RegistrationInterval interface{} `yaml:"registration_interval,omitempty"`

	/*CcEndpoint - Descr: URL for CC Default: <nil>
*/
	CcEndpoint interface{} `yaml:"cc_endpoint,omitempty"`

	/*Route - Descr: Hostname at which broker will be accessed Default: pivotal-rabbitmq-broker
*/
	Route interface{} `yaml:"route,omitempty"`

}