package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Number of audit file rotations to keep Default: 30
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

}