package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*ServerAuditFileRotations - Descr: Number of audit file rotations to keep Default: 30
*/
	ServerAuditFileRotations interface{} `yaml:"server_audit_file_rotations,omitempty"`

	/*GaleraHealthcheck - Descr: Password used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

	/*ServerAuditFileRotateSizeInMb - Descr: Size in MB of each audit log file Default: 100
*/
	ServerAuditFileRotateSizeInMb interface{} `yaml:"server_audit_file_rotate_size_in_mb,omitempty"`

	/*DisableAutoSst - Descr: When disable_auto_sst is true, nodes unable to IST will be prevented from automatically deleting their data and performing an SST Default: true
*/
	DisableAutoSst interface{} `yaml:"disable_auto_sst,omitempty"`

	/*LogConflicts - Descr: Defines whether the node logs additional information about conflicts. The values that were in conflict are logged, so it is possible for user data to end up in the logs. Default: true
*/
	LogConflicts interface{} `yaml:"log_conflicts,omitempty"`

	/*ServerAuditExcludedUsers - Descr: Other database users to exclude from audit logging Default: []
*/
	ServerAuditExcludedUsers interface{} `yaml:"server_audit_excluded_users,omitempty"`

	/*InterruptNotifyCmd - Descr: Path to a binary to run when SST is prevented from running Default: 
*/
	InterruptNotifyCmd interface{} `yaml:"interrupt_notify_cmd,omitempty"`

	/*BinlogExpireDays - Descr: Time in days to store binlogs before purging Default: 60
*/
	BinlogExpireDays interface{} `yaml:"binlog_expire_days,omitempty"`

	/*ClusterHealth - Descr: Password for the cluster logger health user Default: <nil>
*/
	ClusterHealth *ClusterHealth `yaml:"cluster_health,omitempty"`

	/*MaxOpenFiles - Descr: Configure this number to be comfortably larger than the maximum number of tables you expect the database to support. Default: 65536
*/
	MaxOpenFiles interface{} `yaml:"max_open_files,omitempty"`

	/*BinlogEnabled - Descr: Enable binlogs across all nodes Default: true
*/
	BinlogEnabled interface{} `yaml:"binlog_enabled,omitempty"`

	/*ServerAuditEvents - Descr: Enable audit logging and specify types of events that will be logged. If null, then logging is disabled Default: <nil>
*/
	ServerAuditEvents interface{} `yaml:"server_audit_events,omitempty"`

}