package garden 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GardenJob struct {

	/*Garden - Descr: List of comma-separated hosts that should skip connecting to the proxy Default: <nil>
*/
	Garden *Garden `yaml:"garden,omitempty"`

}