package garden 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GardenJob struct {

	/*Garden - Descr: List of CIDR blocks to which containers will be denied access. Default: []
*/
	Garden *Garden `yaml:"garden,omitempty"`

}