package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Authentication struct {

	/*Policy - Descr: Number of seconds in which lockoutAfterFailures failures must occur in order for account to be locked Default: 3600
*/
	Policy *AuthenticationPolicy `yaml:"policy,omitempty"`

}