package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Authentication struct {

	/*Policy - Descr: Number of seconds to lock out an account when lockoutAfterFailures failures is exceeded Default: 300
*/
	Policy *AuthenticationPolicy `yaml:"policy,omitempty"`

}