package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaJob struct {

	/*Login - Descr: Global property to sign Local/SP requests Default: true
*/
	Login *Login `yaml:"login,omitempty"`

	/*Uaa - Descr: The file to be used for configuring the LDAP authentication. Options are: 'simple-bind', 'search-and-bind', 'search-and-compare' Default: search-and-bind
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Uaadb - Descr: The UAA database IP address Default: <nil>
*/
	Uaadb *Uaadb `yaml:"uaadb,omitempty"`

	/*Env - Descr: Set No_Proxy across the VMs Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Domain - Descr: Deprecated. Use uaa.url for setting the location of UAA Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

}