package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaJob struct {

	/*Domain - Descr: Deprecated. Use uaa.url for setting the location of UAA Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Uaadb - Descr: The UAA database IP address Default: <nil>
*/
	Uaadb *Uaadb `yaml:"uaadb,omitempty"`

	/*Uaa - Descr: The url to use as the issuer URI Default: <nil>
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Login - Descr: Deprecated. Use uaa.ldap.localPasswordCompare - login.ldap prefix is used for backwards compatibility to enable ldap from login config Default: true
*/
	Login *Login `yaml:"login,omitempty"`

	/*Env - Descr: Set No_Proxy across the VMs Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

}