package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaPassword struct {

	/*Policy - Descr: Maximum number of characters required for password to be considered valid Default: 255
*/
	Policy *PasswordPolicy `yaml:"policy,omitempty"`

}