package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*QuotaEnforcer - Descr: In seconds, the interval that the Quota Enforcer pauses between checks for violators and reformers Default: 1
*/
	QuotaEnforcer *QuotaEnforcer `yaml:"quota_enforcer,omitempty"`

}