package deploy_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AppPush struct {

	/*Memory - Descr: App Push Memory limit for the Service Broker Application Default: 1024
*/
	Memory interface{} `yaml:"memory,omitempty"`

	/*Timeout - Descr: App Push Timeout for the Service Broker Application Default: 180
*/
	Timeout interface{} `yaml:"timeout,omitempty"`

}