package deploy_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Clients struct {

	/*SpringCloudBroker - Descr: UAA Client Secret Default: <nil>
*/
	SpringCloudBroker *ClientsSpringCloudBroker `yaml:"spring_cloud_broker,omitempty"`

}