package deploy_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SpringCloudBroker struct {

	/*MessageBusType - Descr: The message bus type to use when communicating with workers Default: rabbitmq
*/
	MessageBusType interface{} `yaml:"message_bus_type,omitempty"`

	/*EncryptionKey - Descr: Specifies the key to be used when encrypting sessions Default: <nil>
*/
	EncryptionKey interface{} `yaml:"encryption_key,omitempty"`

	/*AppName - Descr: Name of the Service Broker Application Default: spring-cloud-broker
*/
	AppName interface{} `yaml:"app_name,omitempty"`

	/*AppPush - Descr: App Push Memory limit for the Service Broker Application Default: 1024
*/
	AppPush *AppPush `yaml:"app_push,omitempty"`

	/*Broker - Descr: Broker basic auth password Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Buildpack - Descr: Buildpack to use Default: 
*/
	Buildpack interface{} `yaml:"buildpack,omitempty"`

	/*Uaa - Descr: Client ID of the UAA admin client Default: <nil>
*/
	Uaa *SpringCloudBrokerUaa `yaml:"uaa,omitempty"`

	/*ProductName - Descr: Product Name Default: p-spring-cloud-services
*/
	ProductName interface{} `yaml:"product_name,omitempty"`

	/*Worker - Descr: Worker basic auth user Default: <nil>
*/
	Worker *Worker `yaml:"worker,omitempty"`

	/*Instances - Descr: Username with access to instances space Default: <nil>
*/
	Instances *Instances `yaml:"instances,omitempty"`

	/*BrokerDashboardSecret - Descr: The broker dashboard secret Default: <nil>
*/
	BrokerDashboardSecret interface{} `yaml:"broker_dashboard_secret,omitempty"`

	/*PersistenceStoreType - Descr: Use MySQL or custom DB for persistence store Default: mysql
*/
	PersistenceStoreType interface{} `yaml:"persistence_store_type,omitempty"`

	/*Version - Descr: Broker version Default: 3
*/
	Version interface{} `yaml:"version,omitempty"`

	/*Cf - Descr: Password of the CF admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*AppUri - Descr: URI of the Service Broker Application Default: spring-cloud-broker
*/
	AppUri interface{} `yaml:"app_uri,omitempty"`

}