package deploy_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Worker struct {

	/*ClientId - Descr: Worker Client ID Default: p-spring-cloud-services-worker
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

	/*Password - Descr: Worker basic auth password Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*User - Descr: Worker basic auth user Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*ClientSecret - Descr: Worker Client Secret Default: <nil>
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

}