package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServerJob struct {

	/*EtcdMetricsServer - Descr: address of ETCD server to instrument Default: 127.0.0.1
*/
	EtcdMetricsServer *EtcdMetricsServer `yaml:"etcd_metrics_server,omitempty"`

}