package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServer struct {

	/*Etcd - Descr: port of ETCD server to instrument Default: 4001
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*Nats - Descr: NATS server password Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Status - Descr: listening port for metrics server Default: 5678
*/
	Status *Status `yaml:"status,omitempty"`

}