package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServer struct {

	/*Etcd - Descr: address of ETCD server to instrument Default: 127.0.0.1
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*Nats - Descr: NATS server port Default: 4222
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Status - Descr: listening port for metrics server Default: 5678
*/
	Status *Status `yaml:"status,omitempty"`

}