package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServerJob struct {

	/*EtcdMetricsServer - Descr: port of ETCD server to instrument Default: 4001
*/
	EtcdMetricsServer *EtcdMetricsServer `yaml:"etcd_metrics_server,omitempty"`

}