package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Services - Descr: Array of Services the broker provides Default: <nil>
*/
	Services interface{} `yaml:"services,omitempty"`

}