package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*SmokeTests - Descr: Password for generated user to comply with CF password policy, if exists. Default: <nil>
*/
	SmokeTests *CfMysqlSmokeTests `yaml:"smoke_tests,omitempty"`

	/*Mysql - Descr: Admin username used to access MySQL Default: root
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

	/*ExternalHost - Descr: Hostname given for dashboard URLs (e.g. p-mysql.example.com) Default: <nil>
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

	/*Broker - Descr: Array of Services the broker provides Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*Host - Descr: Hostname given to apps by the broker, usually a Load Balancer address or the IP of the first proxy Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Proxy - Descr: Expect proxy to force redirect to HTTPS Default: true
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

}