package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*AdminPassword - Descr: Admin password used to access MySQL Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*Port - Descr: Port used to access MySQL Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

	/*AdminUsername - Descr: Admin username used to access MySQL Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

}