package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Proxy struct {

	/*ApiUsername - Descr: Proxy API username Default: <nil>
*/
	ApiUsername interface{} `yaml:"api_username,omitempty"`

	/*ApiPassword - Descr: Proxy API password Default: <nil>
*/
	ApiPassword interface{} `yaml:"api_password,omitempty"`

	/*ApiForceHttps - Descr: Expect proxy to force redirect to HTTPS Default: true
*/
	ApiForceHttps interface{} `yaml:"api_force_https,omitempty"`

	/*ProxyIps - Descr: Use to construct an array of proxy dashboard url (e.g. https://proxy-INDEX-EXTERNAL_HOST) Default: <nil>
*/
	ProxyIps interface{} `yaml:"proxy_ips,omitempty"`

}