package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SmokeTestsJob struct {

	/*SmokeTests - Descr: Toggles a portion of the suite that exercises Windows platform support Default: false
*/
	SmokeTests *SmokeTests `yaml:"smoke_tests,omitempty"`

}