package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*SkipCertVerify - Descr: When connecting over https, ignore bad ssl certificates Default: false
*/
	SkipCertVerify interface{} `yaml:"skip_cert_verify,omitempty"`

}