package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SyslogDrainBinder struct {

	/*LockedMemoryLimit - Descr: Size (KB) of shell's locked memory limit. Set to 'kernel' to use the kernel's default. Non-numeric values other than 'kernel', 'soft', 'hard', and 'unlimited' will result in an error. Default: unlimited
*/
	LockedMemoryLimit interface{} `yaml:"locked_memory_limit,omitempty"`

	/*DrainUrlTtlSeconds - Descr: Time to live for drain urls in seconds Default: 60
*/
	DrainUrlTtlSeconds interface{} `yaml:"drain_url_ttl_seconds,omitempty"`

	/*Etcd - Descr: PEM-encoded client key Default: 
*/
	Etcd *SyslogDrainBinderEtcd `yaml:"etcd,omitempty"`

	/*Debug - Descr: Boolean value to turn on verbose logging for syslog_drain_binder Default: false
*/
	Debug interface{} `yaml:"debug,omitempty"`

	/*UpdateIntervalSeconds - Descr: Interval on which to poll cloud controller in seconds Default: 15
*/
	UpdateIntervalSeconds interface{} `yaml:"update_interval_seconds,omitempty"`

	/*PollingBatchSize - Descr: Batch size for the poll from cloud controller Default: 1000
*/
	PollingBatchSize interface{} `yaml:"polling_batch_size,omitempty"`

}