package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SyslogDrainBinderJob struct {

	/*Ssl - Descr: When connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Cc - Descr: Password for the bulk api Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*SystemDomain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*MetronEndpoint - Descr: The host used to emit messages to the Metron agent Default: 127.0.0.1
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*Loggregator - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*SyslogDrainBinder - Descr: Batch size for the poll from cloud controller Default: 1000
*/
	SyslogDrainBinder *SyslogDrainBinder `yaml:"syslog_drain_binder,omitempty"`

}