package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Password used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

}