package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ClusterHealth struct {

	/*LogInterval - Descr: Time in seconds between log entries for cluster health Default: 30
*/
	LogInterval interface{} `yaml:"log_interval,omitempty"`

	/*Password - Descr: Password for the cluster logger health user Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}