package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MysqlJob struct {

	/*CfMysql - Descr: Password used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*SyslogAggregator - Descr: TCP port of syslog aggregator Default: <nil>
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

}