package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*MaxOpenFiles - Descr: Configure this number to be comfortably larger than the maximum number of tables you expect the database to support. Default: 65536
*/
	MaxOpenFiles interface{} `yaml:"max_open_files,omitempty"`

	/*ClusterHealth - Descr: Password for the cluster logger health user Default: <nil>
*/
	ClusterHealth *ClusterHealth `yaml:"cluster_health,omitempty"`

	/*InnodbBufferPoolSize - Descr: Optional, the size in bytes of the memory buffer InnoDB uses to cache data and indexes of its tables Default: <nil>
*/
	InnodbBufferPoolSize interface{} `yaml:"innodb_buffer_pool_size,omitempty"`

	/*GcacheSize - Descr: Cache size used by galera (maximum amount of data possible in an IST), in MB Default: 512
*/
	GcacheSize interface{} `yaml:"gcache_size,omitempty"`

	/*ServerAuditFileRotateSizeInMb - Descr: Size in MB of each audit log file Default: 100
*/
	ServerAuditFileRotateSizeInMb interface{} `yaml:"server_audit_file_rotate_size_in_mb,omitempty"`

	/*LogQueriesNotUsingIndexes - Descr: Queries that don't use an index, or that perform a full index scan where the index doesn't limit the number of rows, will be logged to the slow query log. Default: false
*/
	LogQueriesNotUsingIndexes interface{} `yaml:"log_queries_not_using_indexes,omitempty"`

	/*SeededDatabases - Descr: Set of databases to seed Default: map[]
*/
	SeededDatabases interface{} `yaml:"seeded_databases,omitempty"`

	/*CharacterSetServer - Descr: Default character set. Note that while the MariaDB default is latin1, we default to utf8. Default: utf8
*/
	CharacterSetServer interface{} `yaml:"character_set_server,omitempty"`

	/*ClusterIps - Descr: Optional, list of nodes.  Must have the same number of ips as there are nodes in the cluster Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*DatabaseStartupTimeout - Descr: How long the startup script waits for the database to come online (in seconds) Default: <nil>
*/
	DatabaseStartupTimeout interface{} `yaml:"database_startup_timeout,omitempty"`

	/*AdminUsername - Descr: Username for the MySQL server admin user Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*IbLogFileSize - Descr: Size of the ib_log_file used by innodb, in MB Default: 1024
*/
	IbLogFileSize interface{} `yaml:"ib_log_file_size,omitempty"`

	/*WsrepMaxWsRows - Descr: Maximum permitted number of rows per writeset. Default: 131072
*/
	WsrepMaxWsRows interface{} `yaml:"wsrep_max_ws_rows,omitempty"`

	/*GaleraHealthcheck - Descr: Password used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

	/*TmpTableSize - Descr: The maximum size (in bytes) of internal in-memory temporary tables Default: 33554432
*/
	TmpTableSize interface{} `yaml:"tmp_table_size,omitempty"`

	/*InnodbBufferPoolInstances - Descr: Optional, number of buffer pool instances for InnoDB used if innodb_buffer_pool_size > 1GB Default: <nil>
*/
	InnodbBufferPoolInstances interface{} `yaml:"innodb_buffer_pool_instances,omitempty"`

	/*RoadminPassword - Descr: Password for the MySQL server read-only admin user Default: <nil>
*/
	RoadminPassword interface{} `yaml:"roadmin_password,omitempty"`

	/*BinlogExpireDays - Descr: Time in days to store binlogs before purging Default: 60
*/
	BinlogExpireDays interface{} `yaml:"binlog_expire_days,omitempty"`

	/*PreviousAdminUsername - Descr: Previous username of the MySQL server admin user to be removed Default: <nil>
*/
	PreviousAdminUsername interface{} `yaml:"previous_admin_username,omitempty"`

	/*MaxAllowedPacket - Descr: The maximum size in bytes of a packet or a generated/intermediate string Default: 256M
*/
	MaxAllowedPacket interface{} `yaml:"max_allowed_packet,omitempty"`

	/*ServerAuditEvents - Descr: Enable audit logging and specify types of events that will be logged. If null, then logging is disabled Default: <nil>
*/
	ServerAuditEvents interface{} `yaml:"server_audit_events,omitempty"`

	/*MaxConnections - Descr: Maximum total number of database connections for the node Default: 1500
*/
	MaxConnections interface{} `yaml:"max_connections,omitempty"`

	/*WsrepDebug - Descr: When set to 1 or 2, the database server logs additional events surrounding errors to help in identifying and correcting problems. Note, these logs are written to disk and to syslog. Enabling this will possibly expose unencrypted application data. Default: 0
*/
	WsrepDebug interface{} `yaml:"wsrep_debug,omitempty"`

	/*CollationServer - Descr: Default collation. Use SHOW COLLATION to view the valid collations for your character set. Default: utf8_unicode_ci
*/
	CollationServer interface{} `yaml:"collation_server,omitempty"`

	/*DisableAutoSst - Descr: When disable_auto_sst is true, nodes unable to IST will be prevented from automatically deleting their data and performing an SST Default: true
*/
	DisableAutoSst interface{} `yaml:"disable_auto_sst,omitempty"`

	/*GaleraPort - Descr: Port which Galera Cluster uses for communication across nodes Default: 4567
*/
	GaleraPort interface{} `yaml:"galera_port,omitempty"`

	/*BinlogEnabled - Descr: Enable binlogs across all nodes Default: true
*/
	BinlogEnabled interface{} `yaml:"binlog_enabled,omitempty"`

	/*WsrepMaxWsSize - Descr: Maximum permitted size in bytes per writeset. Default: 1073741824
*/
	WsrepMaxWsSize interface{} `yaml:"wsrep_max_ws_size,omitempty"`

	/*ServerAuditExcludedUsers - Descr: Other database users to exclude from audit logging Default: []
*/
	ServerAuditExcludedUsers interface{} `yaml:"server_audit_excluded_users,omitempty"`

	/*InnodbLockWaitTimeout - Descr: Optional, time in seconds that an InnoDB transaction waits for an InnoDB row lock Default: <nil>
*/
	InnodbLockWaitTimeout interface{} `yaml:"innodb_lock_wait_timeout,omitempty"`

	/*InterruptNotifyCmd - Descr: Path to a binary to run when SST is prevented from running Default: 
*/
	InterruptNotifyCmd interface{} `yaml:"interrupt_notify_cmd,omitempty"`

	/*LogConflicts - Descr: Defines whether the node logs additional information about conflicts. The values that were in conflict are logged, so it is possible for user data to end up in the logs. Default: true
*/
	LogConflicts interface{} `yaml:"log_conflicts,omitempty"`

	/*MaxHeapTableSize - Descr: The maximum size (in rows) to which user-created MEMORY tables are permitted to grow Default: 16777216
*/
	MaxHeapTableSize interface{} `yaml:"max_heap_table_size,omitempty"`

	/*Port - Descr: Port the mysql server should bind to Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Userstat - Descr: Enables user statistics, adding several new information schema tables and new FLUSH and SHOW commands. Default: false
*/
	Userstat interface{} `yaml:"userstat,omitempty"`

	/*SkipNameResolve - Descr: Do not restrict connections to database based on hostname Default: true
*/
	SkipNameResolve interface{} `yaml:"skip_name_resolve,omitempty"`

	/*ServerAuditFileRotations - Descr: Number of audit file rotations to keep Default: 30
*/
	ServerAuditFileRotations interface{} `yaml:"server_audit_file_rotations,omitempty"`

	/*RoadminEnabled - Descr: Whether read only user is enabled Default: false
*/
	RoadminEnabled interface{} `yaml:"roadmin_enabled,omitempty"`

	/*AdminPassword - Descr: Password for the MySQL server admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

}