package config

type Config struct {
	AZs                                       []string
	StemcellName                              string
	NetworkName                               string
	SystemDomain                              string
	AppDomains                                []string
	AdminPassword                             string
	MySQLIPs                                  []string
	MySQLBootstrapUser                        string
	MySQLBootstrapPassword                    string
	AllowSSHAccess                            bool
	SkipSSLCertVerify                         bool
	NATSUser                                  string
	NATSPassword                              string
	NATSPort                                  int
	NATSMachines                              []string
	JWTVerificationKey                        string
	ConsulCaCert                              string
	ConsulEncryptKeys                         []string
	ConsulAgentCert                           string
	ConsulAgentKey                            string
	ConsulServerCert                          string
	ConsulServerKey                           string
	ErrandVMType                              string
	SmokeTestsPassword                        string
	UAALoginProtocol                          string
	LoggregratorIPs                           []string
	LoggregratorVMType                        string
	DopplerSecret                             string
	EtcdMachines                              []string
	MetronZone                                string
	MetronSecret                              string
	SyslogAddress                             string
	SyslogPort                                int
	SyslogTransport                           string
	DopplerIPs                                []string
	DopplerVMType                             string
	DopplerZone                               string
	DopplerMessageDrainBufferSize             int
	DopplerSharedSecret                       string
	CCBulkAPIPassword                         string
	CCBulkAPIUser                             string
	DiegoCellVMType                           string
	DiegoCellPersistentDiskType               string
	DiegoCellIPs                              []string
	ConsulIPs                                 []string
	BBSCACert                                 string
	BBSClientCert                             string
	BBSClientKey                              string
	BBSServerCert                             string
	BBSServerKey                              string
	DiegoBrainVMType                          string
	DiegoBrainPersistentDiskType              string
	DiegoBrainIPs                             []string
	BBSRequireSSL                             bool
	CCUploaderJobPollInterval                 int
	CCInternalAPIUser                         string
	CCInternalAPIPassword                     string
	CCBulkBatchSize                           int
	CCFetchTimeout                            int
	FSListenAddr                              string
	FSStaticDirectory                         string
	FSDebugAddr                               string
	FSLogLevel                                string
	MetronPort                                int
	SSHProxyClientSecret                      string
	CCExternalPort                            int
	TrafficControllerURL                      string
	RouterMachines                            []string
	EtcdServerCert                            string
	EtcdServerKey                             string
	EtcdClientCert                            string
	EtcdClientKey                             string
	EtcdPeerCert                              string
	EtcdPeerKey                               string
	MySQLProxyIPs                             []string
	UAAVMType                                 string
	UAAInstances                              int
	DiegoDBPassphrase                         string
	DiegoDBVMType                             string
	DiegoDBPersistentDiskType                 string
	DiegoDBIPs                                []string
	SAMLServiceProviderKey                    string
	SAMLServiceProviderCertificate            string
	JWTSigningKey                             string
	AdminSecret                               string
	UAADBUserName                             string
	UAADBPassword                             string
	PushAppsManagerPassword                   string
	SystemServicesPassword                    string
	SystemVerificationPassword                string
	OpentsdbFirehoseNozzleClientSecret        string
	IdentityClientSecret                      string
	LoginClientSecret                         string
	PortalClientSecret                        string
	AutoScalingServiceClientSecret            string
	SystemPasswordsClientSecret               string
	CCServiceDashboardsClientSecret           string
	GoRouterClientSecret                      string
	NotificationsClientSecret                 string
	NotificationsUIClientSecret               string
	CloudControllerUsernameLookupClientSecret string
	CCRoutingClientSecret                     string
	AppsMetricsClientSecret                   string
	AppsMetricsProcessingClientSecret         string
	SelfServiceLinksEnabled                   bool
	SignupsEnabled                            bool
	CompanyName                               string
	ProductLogo                               string
	SquareLogo                                string
	FooterLegalText                           string
	LDAPUrl                                   string
	LDAPUserDN                                string
	LDAPUserPassword                          string
	LDAPSearchBase                            string
	LDAPSearchFilter                          string
	LDAPMailAttributeName                     string
	LDAPEnabled                               bool
	CloudControllerWorkerInstances            int
	CloudControllerWorkerVMType               string
	NFSServerAddress                          string
	SharePath                                 string
	StagingUploadUser                         string
	StagingUploadPassword                     string
	DbEncryptionKey                           string
	InternalAPIUser                           string
	InternalAPIPassword                       string
	CCDBUsername                              string
	CCDBPassword                              string
	CloudControllerInstances                  int
	CloudControllerVMType                     string
	HostKeyFingerprint                        string
	SupportAddress                            string
	MinCliVersion                             string
	ClockGlobalVMType                         string
	HAProxySSLPem                             string
	HAProxySkip                               bool
	HAProxyVMType                             string
	HAProxyIPs                                []string
	MySQLProxyVMType                          string
	MySQLProxyAPIUsername                     string
	MySQLProxyAPIPassword                     string
	MySQLProxyExternalHost                    string
	RouterSSLCert                             string
	RouterSSLKey                              string
	RouterVMType                              string
	RouterEnableSSL                           bool
	RouterUser                                string
	RouterPass                                string
	NFSVMType                                 string
	NFSIPs                                    []string
	NFSPersistentDiskType                     string
	NFSAllowFromNetworkCIDR                   []string
	EtcdVMType                                string
	EtcdPersistentDiskType                    string
	NatsVMType                                string
	ConsulVMType                              string
	MySQLVMType                               string
	MySQLPersistentDiskType                   string
	MySQLAdminPassword                        string
	ConsoleDBUserName                         string
	ConsoleDBPassword                         string
}

func (c *Config) MySQLProxyHost() string {
	return c.MySQLProxyIPs[0]
}
