package config

import (
	"github.com/enaml-ops/pluginlib/pcli"
	"github.com/enaml-ops/pluginlib/pluginutil"
	"gopkg.in/urfave/cli.v2"
)

func NewSecret(c *cli.Context) (*Secret, error) {
	s := Secret{}
	err := pcli.UnmarshalFlags(&s, c)
	if err != nil {
		return nil, err
	}

	s.AutoscaleBrokerPassword = pluginutil.NewPassword(16)
	return &s, nil
}

// Secret contains the secrets for a Cloud Foundry deployment.
type Secret struct {
	AdminPassword                             string
	MySQLBootstrapPassword                    string `omg:"mysql-bootstrap-password"`
	NATSPassword                              string `omg:"nats-pass"`
	SmokeTestsPassword                        string
	DopplerSecret                             string `omg:"doppler-client-secret"`
	DopplerSharedSecret                       string
	CCBulkAPIPassword                         string `omg:"cc-bulk-api-password"`
	CCInternalAPIPassword                     string `omg:"cc-internal-api-password"`
	SSHProxyClientSecret                      string `omg:"ssh-proxy-uaa-secret"`
	DiegoDBPassphrase                         string `omg:"diego-db-passphrase"`
	AdminSecret                               string `omg:"uaa-admin-secret"`
	UAADBPassword                             string `omg:"db-uaa-password"`
	PushAppsManagerPassword                   string
	SystemServicesPassword                    string
	SystemVerificationPassword                string
	OpentsdbFirehoseNozzleClientSecret        string
	IdentityClientSecret                      string
	LoginClientSecret                         string
	PortalClientSecret                        string
	AutoScalingServiceClientSecret            string `omg:"autoscaling-service-client-secret"`
	SystemPasswordsClientSecret               string
	CCServiceDashboardsClientSecret           string `omg:"cc-service-dashboards-client-secret"`
	GoRouterClientSecret                      string `omg:"gorouter-client-secret"`
	NotificationsClientSecret                 string
	NotificationsUIClientSecret               string `omg:"notifications-ui-client-secret"`
	CloudControllerUsernameLookupClientSecret string
	CCRoutingClientSecret                     string `omg:"cc-routing-client-secret"`
	AppsMetricsClientSecret                   string
	AppsMetricsProcessingClientSecret         string
	LDAPUserPassword                          string `omg:"uaa-ldap-user-password,optional"`
	DbEncryptionKey                           string `omg:"cc-db-encryption-key"`
	CCDBPassword                              string `omg:"db-ccdb-password"`
	StagingUploadPassword                     string `omg:"cc-staging-upload-password"`
	MySQLProxyAPIPassword                     string `omg:"mysql-proxy-api-password"`
	RouterPass                                string
	MySQLAdminPassword                        string   `omg:"mysql-admin-password"`
	ConsoleDBPassword                         string   `omg:"db-console-password"`
	ConsulEncryptKeys                         []string `omg:"consul-encryption-key"`
	AppUsageDBPassword                        string   `omg:"db-app_usage-password"`
	AppsManagerSecretToken                    string
	AutoscaleBrokerPassword                   string `omg:"-"` // always autogenerated
	AutoscaleDBPassword                       string `omg:"db-autoscale-password"`
	NotificationsDBPassword                   string `omg:"db-notifications-password"`
}
