package dea_next 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DeaNextJob struct {

	/*Cc - Descr: User name to access internal endpoints Default: internal_user
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*Router - Descr: Interval at which the router requests routes to be registered. Default: 20
*/
	Router *Router `yaml:"router,omitempty"`

	/*Hm9000 - Descr: PEM-encoded client key Default: <nil>
*/
	Hm9000 *Hm9000 `yaml:"hm9000,omitempty"`

	/*DeaNext - Descr: Duration to wait before shutting down, in seconds. Default: 115
*/
	DeaNext *DeaNext `yaml:"dea_next,omitempty"`

	/*Nats - Descr: password for NATS login Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*SystemDomain - Descr: DNS domain name for this Cloud Foundry deployment Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*MetronEndpoint - Descr: The host used to emit messages to the Metron agent Default: 127.0.0.1
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*MetronAgent - Descr: The port used to emit messages to the Metron agent Default: 3457
*/
	MetronAgent *MetronAgent `yaml:"metron_agent,omitempty"`

	/*DiskQuotaEnabled - Descr: disk quota must be disabled to use warden-inside-warden with the warden cpi Default: true
*/
	DiskQuotaEnabled interface{} `yaml:"disk_quota_enabled,omitempty"`

}