package cflinuxfs2_rootfs_setup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cflinuxfs2Rootfs struct {

	/*TrustedCerts - Descr: certficates to add to the rootfs trust store Default: <nil>
*/
	TrustedCerts interface{} `yaml:"trusted_certs,omitempty"`

}