package registry 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cache struct {

	/*Host - Descr: IP address of the cache host Default: 
*/
	Host interface{} `yaml:"host,omitempty"`

}