package registry 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RegistryJob struct {

	/*Docker - Descr: What port to run the Docker Registry v2 API on Default: 5000
*/
	Docker *Docker `yaml:"docker,omitempty"`

}