package blackbox 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Blackbox struct {

	/*Syslog - Descr: address for syslog drain (including port) Default: <nil>
*/
	Syslog *Syslog `yaml:"syslog,omitempty"`

}