package blackbox 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BlackboxJob struct {

	/*Blackbox - Descr: address for syslog drain (including port) Default: <nil>
*/
	Blackbox *Blackbox `yaml:"blackbox,omitempty"`

}