package test_service_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Url - Descr: Gemfire service broker API address Default: <nil>
*/
	Url interface{} `yaml:"url,omitempty"`

}