package test_service_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cc struct {

	/*Api - Descr: Password for authentication Default: <nil>
*/
	Api *Api `yaml:"api,omitempty"`

	/*AppDomain - Descr: Cloud Controller Application Domain Default: <nil>
*/
	AppDomain interface{} `yaml:"app_domain,omitempty"`

}