package hm9000 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Etcd struct {

	/*RequireSsl - Descr: Require TLS for communication with ETCD Default: false
*/
	RequireSsl interface{} `yaml:"require_ssl,omitempty"`

	/*Machines - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*ClientCert - Descr: PEM-encoded client certificate to communicate with ETCD Default: <nil>
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

	/*ClientKey - Descr: PEM-encoded client key to communicate with ETCD Default: <nil>
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

	/*CaCert - Descr: PEM-encoded CA certificate Default: <nil>
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

}