package hm9000 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Hm9000Job struct {

	/*Cc - Descr: Password for hm9000 API Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*DeaNext - Descr: Heartbeat interval for DEAs Default: <nil>
*/
	DeaNext *DeaNext `yaml:"dea_next,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*MetronAgent - Descr: Incoming port for dropsonde log messages Default: 3457
*/
	MetronAgent *MetronAgent `yaml:"metron_agent,omitempty"`

	/*Hm9000 - Descr: PEM-encoded client key to communicate with ETCD Default: <nil>
*/
	Hm9000 *Hm9000 `yaml:"hm9000,omitempty"`

	/*Nats - Descr:  Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}