package docker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ulimit struct {

	/*Nofile - Descr: Maximum number of open files Default: 8192
*/
	Nofile interface{} `yaml:"nofile,omitempty"`

}