package fetch_containers_images 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Services - Descr: Services and plans offered by the broker Default: <nil>
*/
	Services interface{} `yaml:"services,omitempty"`

}