package fetch_containers_images 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type FetchContainersImages struct {

	/*DockerUrl - Descr: Docker URL (IP/Socket) Default: <nil>
*/
	DockerUrl interface{} `yaml:"docker_url,omitempty"`

}