package minio_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Credential struct {

	/*Accesskey - Descr: The access key the server should accept Default: <nil>
*/
	Accesskey interface{} `yaml:"accesskey,omitempty"`

	/*Secretkey - Descr: The secret key the server should accept Default: <nil>
*/
	Secretkey interface{} `yaml:"secretkey,omitempty"`

}