package loggregator_acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type LoggregatorEndpoint struct {

	/*SharedSecret - Descr:  Default: <nil>
*/
	SharedSecret interface{} `yaml:"shared_secret,omitempty"`

}