package loggregator_acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type LoggregatorAcceptanceTests struct {

	/*AdminPassword - Descr:  Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*LoginRequired - Descr:  Default: <nil>
*/
	LoginRequired interface{} `yaml:"login_required,omitempty"`

	/*AdminUser - Descr:  Default: <nil>
*/
	AdminUser interface{} `yaml:"admin_user,omitempty"`

}