package loggregator_acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type LoggregatorAcceptanceTestsJob struct {

	/*LoggregatorEndpoint - Descr:  Default: <nil>
*/
	LoggregatorEndpoint *LoggregatorEndpoint `yaml:"loggregator_endpoint,omitempty"`

	/*LoggregatorAcceptanceTests - Descr:  Default: <nil>
*/
	LoggregatorAcceptanceTests *LoggregatorAcceptanceTests `yaml:"loggregator_acceptance_tests,omitempty"`

	/*Loggregator - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*SystemDomain - Descr: for computing the Traffic Controller URL Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*Ssl - Descr:  Default: <nil>
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*MetronAgent - Descr: port for tests to send metrics to metron Default: <nil>
*/
	MetronAgent *MetronAgent `yaml:"metron_agent,omitempty"`

}