package loggregator_acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MetronAgent struct {

	/*DropsondeIncomingPort - Descr: port for tests to send metrics to metron Default: <nil>
*/
	DropsondeIncomingPort interface{} `yaml:"dropsonde_incoming_port,omitempty"`

}