package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BackupServer struct {

	/*Port - Descr: Port number of server that generates backups Default: 8081
*/
	Port interface{} `yaml:"port,omitempty"`

}