package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: List of IP address of servers which can generate backups Default: <nil>
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

	/*Proxy - Descr: IP address for the arbitrator nodes of the MySQL cluster to exclude from backups Default: <nil>
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

}