package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysqlBackup struct {

	/*BackupServer - Descr: Port number of server that generates backups Default: 8081
*/
	BackupServer *BackupServer `yaml:"backup-server,omitempty"`

	/*BackupAllMasters - Descr: If true, backups will be taken from all master nodes Default: false
*/
	BackupAllMasters interface{} `yaml:"backup-all-masters,omitempty"`

	/*SymmetricKey - Descr: Symmetric Key used to encrypt backups Default: <nil>
*/
	SymmetricKey interface{} `yaml:"symmetric_key,omitempty"`

	/*BackupClient - Descr: Folder to download / prepare backups Default: /var/vcap/store/mysql-backups-tmp
*/
	BackupClient *BackupClient `yaml:"backup-client,omitempty"`

	/*EndpointCredentials - Descr: Password used by backup client to stream a backup from the mysql node Default: <nil>
*/
	EndpointCredentials *EndpointCredentials `yaml:"endpoint_credentials,omitempty"`

}