package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*ClusterIps - Descr: List of IP address of servers which can generate backups Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

}