package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Proxy struct {

	/*ArbitratorIp - Descr: IP address for the arbitrator nodes of the MySQL cluster to exclude from backups Default: <nil>
*/
	ArbitratorIp interface{} `yaml:"arbitrator_ip,omitempty"`

}