package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StreamingMysqlBackupClientJob struct {

	/*CfMysql - Descr: IP address for the arbitrator nodes of the MySQL cluster to exclude from backups Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*CfMysqlBackup - Descr: If true, backups will be taken from all master nodes Default: false
*/
	CfMysqlBackup *CfMysqlBackup `yaml:"cf-mysql-backup,omitempty"`

}