package cache 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CacheJob struct {

	/*Docker - Descr: Log verbosity level for Redis cache server Default: warning
*/
	Docker *Docker `yaml:"docker,omitempty"`

}