package cache 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cache struct {

	/*Redis - Descr: Log verbosity level for Redis cache server Default: warning
*/
	Redis *Redis `yaml:"redis,omitempty"`

}