package cache 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Docker struct {

	/*Cache - Descr: Log verbosity level for Redis cache server Default: warning
*/
	Cache *Cache `yaml:"cache,omitempty"`

}