package metron_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MetronAgentJob struct {

	/*MetronAgent - Descr: DEPRECATED Default: false
*/
	MetronAgent *MetronAgent `yaml:"metron_agent,omitempty"`

	/*Loggregator - Descr: CA root required for key/cert verification Default: 
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*SyslogDaemonConfig - Descr: Custom rule for syslog forward daemon Default: 
*/
	SyslogDaemonConfig *SyslogDaemonConfig `yaml:"syslog_daemon_config,omitempty"`

	/*MetronEndpoint - Descr: Shared secret used to verify cryptographically signed dropsonde messages Default: <nil>
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

}