package test_cluster_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Gemfire struct {

	/*Locator - Descr: Port the Locator is listening on Default: 55221
*/
	Locator *Locator `yaml:"locator,omitempty"`

	/*Plans - Descr: Configuration for plans deployed by product Default: []
*/
	Plans interface{} `yaml:"plans,omitempty"`

}