package test_cluster_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Locator struct {

	/*Plan2Addresses - Descr: List of GemFire Locator addresses for plan 2 of the form X.X.X.X Default: <nil>
*/
	Plan2Addresses interface{} `yaml:"plan_2_addresses,omitempty"`

	/*Plan3Addresses - Descr: List of GemFire Locator addresses for plan 3 of the form X.X.X.X Default: <nil>
*/
	Plan3Addresses interface{} `yaml:"plan_3_addresses,omitempty"`

	/*Port - Descr: Port the Locator is listening on Default: 55221
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Plan1Addresses - Descr: List of GemFire Locator addresses for plan 1 of the form X.X.X.X Default: <nil>
*/
	Plan1Addresses interface{} `yaml:"plan_1_addresses,omitempty"`

}