package test_cluster_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestClusterHealthJob struct {

	/*Gemfire - Descr: Configuration for plans deployed by product Default: []
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

}