package test_cluster_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestClusterHealthJob struct {

	/*Gemfire - Descr: List of GemFire Locator addresses for plan 1 of the form X.X.X.X Default: <nil>
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

}