package deploy_autoscaling 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AutoscalingService struct {

	/*Secret - Descr: UAA Client Secret Default: <nil>
*/
	Secret interface{} `yaml:"secret,omitempty"`

}