package deploy_autoscaling 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Password - Descr: Broker basic auth password Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*User - Descr: Broker basic auth user Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

}