package deploy_autoscaling 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Clients struct {

	/*AutoscalingService - Descr: UAA Client Secret Default: <nil>
*/
	AutoscalingService *AutoscalingService `yaml:"autoscaling_service,omitempty"`

}