package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BackupGenerator struct {

	/*ClusterIps - Descr: List of IP address of servers which can generate backups Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*Port - Descr: Port number of server that generates backups Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Endpoint - Descr: Endpoint to hit to generate a backup (include a leading slash) Default: <nil>
*/
	Endpoint interface{} `yaml:"endpoint,omitempty"`

	/*Credentials - Descr: Username used by backup client to stream a backup from the mysql node Default: <nil>
*/
	Credentials *Credentials `yaml:"credentials,omitempty"`

}