package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StreamingMysqlBackupClientJob struct {

	/*StreamingMysqlBackupClient - Descr: Folder to download / prepare backups Default: /var/vcap/data/mysql-backups-tmp
*/
	StreamingMysqlBackupClient *StreamingMysqlBackupClient `yaml:"streaming-mysql-backup-client,omitempty"`

}