package cf_containers_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cf struct {

	/*ApiUrl - Descr: URL of the CloudFoundry Cloud Controller Default: <nil>
*/
	ApiUrl interface{} `yaml:"api_url,omitempty"`

}