package cf_containers_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nats struct {

	/*Machines - Descr: Array of IPs of each NATS cluster member Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*User - Descr: Username for broker to connect to NATS Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Port - Descr: IP port of Cloud Foundry NATS server Default: 4222
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Password - Descr: Password for broker to connect to NATS Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}