package cf_containers_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Unicorn struct {

	/*Port - Descr: Unicorn listen port Default: 80
*/
	Port interface{} `yaml:"port,omitempty"`

	/*WorkerProcesses - Descr: Unicorn worker processes. If the number of worker processes > 1 then you must disable the broker.allocate_docker_host_ports property Default: 1
*/
	WorkerProcesses interface{} `yaml:"worker_processes,omitempty"`

}