package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerRegistrar struct {

	/*Orgs - Descr: Enable service access for specific organizations. By default, access is enabled for all orgs. Default: []
*/
	Orgs interface{} `yaml:"orgs,omitempty"`

}