package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Service struct {

	/*Name - Descr: Offered service name Default: p-rabbitmq
*/
	Name interface{} `yaml:"name,omitempty"`

}