package destroy_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Notifications struct {

	/*AppDomain - Descr: Domain used to host application Default: <nil>
*/
	AppDomain interface{} `yaml:"app_domain,omitempty"`

	/*Organization - Descr: Organization where the app is deployed Default: <nil>
*/
	Organization interface{} `yaml:"organization,omitempty"`

	/*Space - Descr: Space where the app is deployed Default: <nil>
*/
	Space interface{} `yaml:"space,omitempty"`

	/*Cf - Descr: Username of the CF admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

}