package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BbsJob struct {

	/*Diego - Descr: EXPERIMENTAL: connection string to use for SQL backend [username:password@tcp(1.1.1.1:1234)/database] Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}