package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Bbs - Descr: capacity of the tls client cache Default: <nil>
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

}