package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Name - Descr: Service name displayed in the catalog metadata Default: p-rabbitmq
*/
	Name interface{} `yaml:"name,omitempty"`

}