package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SyslogDrainBinderJob struct {

	/*SyslogDrainBinder - Descr: Interval on which to poll cloud controller in seconds Default: 15
*/
	SyslogDrainBinder *SyslogDrainBinder `yaml:"syslog_drain_binder,omitempty"`

	/*Cc - Descr: API URI of cloud controller Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*MetronEndpoint - Descr: The port used to emit dropsonde messages to the Metron agent Default: 3457
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*Loggregator - Descr: Number of concurrent requests to ETCD Default: 10
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*SystemDomain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

}