package cloud_controller_worker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BitsService struct {

	/*PrivateEndpoint - Descr: Private url for the bits-service service Default: 
*/
	PrivateEndpoint interface{} `yaml:"private_endpoint,omitempty"`

	/*PublicEndpoint - Descr: Public url for the bits-service service Default: 
*/
	PublicEndpoint interface{} `yaml:"public_endpoint,omitempty"`

	/*Enabled - Descr: Enable integration of the bits-service incubator (experimental) Default: false
*/
	Enabled interface{} `yaml:"enabled,omitempty"`

}