package baggageclaim 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BaggageclaimJob struct {

	/*BindIp - Descr: IP address on which Baggageclaim should listen for HTTP traffic.
 Default: 0.0.0.0
*/
	BindIp interface{} `yaml:"bind_ip,omitempty"`

	/*BindPort - Descr: Port on which Baggageclaim should listen for HTTP traffic.
 Default: 7788
*/
	BindPort interface{} `yaml:"bind_port,omitempty"`

	/*Yeller - Descr: If configured, errors emitted to the logs will also be emitted to Yeller.
This is only really useful for Concourse developers.
 Default: 
*/
	Yeller *Yeller `yaml:"yeller,omitempty"`

}