package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysqlBrokerJob struct {

	/*NetworkName - Descr: The name of the network (needed for the syslog aggregator) Default: <nil>
*/
	NetworkName interface{} `yaml:"network_name,omitempty"`

	/*MaxUserConnectionsDefault - Descr: number of user connections to allow in a plan if not specified Default: 40
*/
	MaxUserConnectionsDefault interface{} `yaml:"max_user_connections_default,omitempty"`

	/*MysqlNode - Descr: Size of the ib_log_file used by innodb, in MB Default: 1024
*/
	MysqlNode *MysqlNode `yaml:"mysql_node,omitempty"`

	/*Networks - Descr: Name of the network the broker will get its IP address from Default: <nil>
*/
	Networks *Networks `yaml:"networks,omitempty"`

	/*AuthUsername - Descr: Broker's basic auth username Default: <nil>
*/
	AuthUsername interface{} `yaml:"auth_username,omitempty"`

	/*SyslogAggregator - Descr: Define whether forwarders should also send non-mysql syslog activity to the aggregator. Default: false
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

	/*SslEnabled - Descr: Determines use of https in dashboard url and in callback uri for calls to UAA Default: true
*/
	SslEnabled interface{} `yaml:"ssl_enabled,omitempty"`

	/*CookieSecret - Descr: A unique secret key, used to sign sessions Default: <nil>
*/
	CookieSecret interface{} `yaml:"cookie_secret,omitempty"`

	/*AuthPassword - Descr: Broker's basic auth password Default: <nil>
*/
	AuthPassword interface{} `yaml:"auth_password,omitempty"`

	/*Services - Descr: Services and plans offered by the broker Default: <nil>
*/
	Services interface{} `yaml:"services,omitempty"`

	/*ExternalHost - Descr: Host used to register a route for the broker with the router in cf-release via NATS. By registering the broker with Cloud Foundry using this route, and using the router for load balancing, the broker can be horizontally scaled. Domain is typically the same as system domain in cf-release. Default: <nil>
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

	/*CcApiUri - Descr: URL of the CloudFoundry Cloud Controller Default: <nil>
*/
	CcApiUri interface{} `yaml:"cc_api_uri,omitempty"`

	/*SkipSslValidation - Descr: Determines whether dashboard verifies SSL certificates when communicating with Cloud Controller and UAA Default: false
*/
	SkipSslValidation interface{} `yaml:"skip_ssl_validation,omitempty"`

	/*Nats - Descr: IP port of Cloud Foundry NATS server Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}