package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CloudControllerNgJob struct {

	/*Uaa - Descr: Used to grant scope for SSO clients for service brokers Default: openid,cloud_controller_service_permissions.read
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Build - Descr: 'build' attribute in the /v2/info endpoint Default: 
*/
	Build interface{} `yaml:"build,omitempty"`

	/*Login - Descr: http or https Default: https
*/
	Login *Login `yaml:"login,omitempty"`

	/*DeaNext - Descr: PEM-encoded CA certificate Default: <nil>
*/
	DeaNext *DeaNext `yaml:"dea_next,omitempty"`

	/*AppSsh - Descr: The oauth client ID of the SSH proxy Default: ssh-proxy
*/
	AppSsh *AppSsh `yaml:"app_ssh,omitempty"`

	/*MetronEndpoint - Descr: The host used to emit messages to the Metron agent Default: 127.0.0.1
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*Domain - Descr: Deprecated in favor of system_domain. Domain where cloud_controller will listen (api.domain) Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*RoutingApi - Descr: Whether to expose the routing_endpoint listed at /v2/info. Enable this after deploying the Routing API Default: false
*/
	RoutingApi *RoutingApi `yaml:"routing_api,omitempty"`

	/*Doppler - Descr: Whether to use ssl for the doppler_logging_endpoint listed at /v2/info Default: true
*/
	Doppler *Doppler `yaml:"doppler,omitempty"`

	/*LoggerEndpoint - Descr: Port for logger endpoint listed at /v2/info Default: 443
*/
	LoggerEndpoint *LoggerEndpoint `yaml:"logger_endpoint,omitempty"`

	/*Description - Descr: 'description' attribute in the /v2/info endpoint Default: 
*/
	Description interface{} `yaml:"description,omitempty"`

	/*NfsServer - Descr: The location at which to mount the nfs share Default: /var/vcap/nfs
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

	/*SupportAddress - Descr: 'support' attribute in the /v2/info endpoint Default: 
*/
	SupportAddress interface{} `yaml:"support_address,omitempty"`

	/*Cc - Descr: The nginx log format string to use when writing to the access log. Default: $host - [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" $proxy_add_x_forwarded_for vcap_request_id:$upstream_http_x_vcap_request_id response_time:$upstream_response_time

*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*SystemDomainOrganization - Descr: An organization that will be created as part of the seeding process. When the system_domain is not shared with (in the list of) app_domains, this is required as the system_domain will be created as a PrivateDomain in this organization. Default: 
*/
	SystemDomainOrganization interface{} `yaml:"system_domain_organization,omitempty"`

	/*Ccdb - Descr: The port of the database server Default: <nil>
*/
	Ccdb *Ccdb `yaml:"ccdb,omitempty"`

	/*Nats - Descr: Password for cc client to connect to NATS Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Hm9000 - Descr: URL of the hm9000 server Default: <nil>
*/
	Hm9000 *Hm9000 `yaml:"hm9000,omitempty"`

	/*Name - Descr: 'name' attribute in the /v2/info endpoint Default: 
*/
	Name interface{} `yaml:"name,omitempty"`

	/*AppDomains - Descr: Array of domains for user apps (example: 'user.app.space.foo', a user app called 'neat' will listen at 'http://neat.user.app.space.foo') Default: <nil>
*/
	AppDomains interface{} `yaml:"app_domains,omitempty"`

	/*Ssl - Descr: specifies that the job is allowed to skip ssl cert verification Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*SystemDomain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*RequestTimeoutInSeconds - Descr: Timeout for requests in seconds. Default: 900
*/
	RequestTimeoutInSeconds interface{} `yaml:"request_timeout_in_seconds,omitempty"`

	/*Version - Descr: 'version' attribute in the /v2/info endpoint Default: 0
*/
	Version interface{} `yaml:"version,omitempty"`

	/*Router - Descr: Support for route services is disabled when no value is configured. Default: 
*/
	Router *Router `yaml:"router,omitempty"`

}