package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*Cf - Descr: Shared domain for pushed apps Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*StandaloneTestsOnly - Descr: Instead of running the full acceptance test suite, only run a minimal set of tests that do not require a running CF deployment Default: false
*/
	StandaloneTestsOnly interface{} `yaml:"standalone_tests_only,omitempty"`

	/*Broker - Descr: Host for the broker. Should be the same as jobs.cf-mysql-broker.properties.external_host Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*TimeoutScale - Descr: scaling multiplier used to determine command timeouts Default: 1
*/
	TimeoutScale interface{} `yaml:"timeout_scale,omitempty"`

	/*SmokeTestPassword - Descr: Password for smoke tests to comply with CF password policy, if exists. Default: @Ma8rtj2vu
*/
	SmokeTestPassword interface{} `yaml:"smoke_test_password,omitempty"`

	/*Proxy - Descr: Expect proxy to force redirect to HTTPS Default: true
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

	/*Standalone - Descr: Hostname of proxy or load balancer used to communicate with MySQL nodes in a standalone deployment Default: <nil>
*/
	Standalone *Standalone `yaml:"standalone,omitempty"`

	/*SmokeTestsOnly - Descr: Instead of running the full acceptance test suite, only run a shorter smoke test Default: true
*/
	SmokeTestsOnly interface{} `yaml:"smoke_tests_only,omitempty"`

	/*Service - Descr: number of user connections to allow in a plan if not specified Default: 40
*/
	Service *Service `yaml:"service,omitempty"`

	/*OrgName - Descr: The name of the Org to run acceptance tests against Default: 
*/
	OrgName interface{} `yaml:"org_name,omitempty"`

}