package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Capi struct {

	/*Stager - Descr: PEM-encoded client key Default: <nil>
*/
	Stager *Stager `yaml:"stager,omitempty"`

}