package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagerJob struct {

	/*Capi - Descr: PEM-encoded client key Default: <nil>
*/
	Capi *Capi `yaml:"capi,omitempty"`

	/*Diego - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Diego *Diego `yaml:"diego,omitempty"`

}