package consul_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConsulAgentJob struct {

	/*Consul - Descr: Agent log level. Default: info
*/
	Consul *Consul `yaml:"consul,omitempty"`

}