package consul_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DnsConfig struct {

	/*AllowStale - Descr: Enables a stale query for DNS information. This allows any Consul server, rather than only the leader, to service the request. Default: false
*/
	AllowStale interface{} `yaml:"allow_stale,omitempty"`

	/*MaxStale - Descr: When allow_stale is specified, this is used to limit how stale results are allowed to be. Default: 5s
*/
	MaxStale interface{} `yaml:"max_stale,omitempty"`

	/*RecursorTimeout - Descr: Timeout used by Consul when recursively querying an upstream DNS server. Default: 5s
*/
	RecursorTimeout interface{} `yaml:"recursor_timeout,omitempty"`

}