package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GorouterJob struct {

	/*RequestTimeoutInSeconds - Descr: Timeout in seconds for Router -> Endpoint roundtrip. Default: 900
*/
	RequestTimeoutInSeconds interface{} `yaml:"request_timeout_in_seconds,omitempty"`

	/*Nats - Descr:  Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Uaa - Descr: Password for UAA client for the gorouter. Default: <nil>
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Dropsonde - Descr: Enable the dropsonde emitter library Default: false
*/
	Dropsonde *Dropsonde `yaml:"dropsonde,omitempty"`

	/*Router - Descr: Host to ping for confirmation of DNS resolution, only used when Routing API is enabled Default: consul.service.cf.internal
*/
	Router *Router `yaml:"router,omitempty"`

	/*RoutingApi - Descr: Port on which routing-api is running. Default: 3000
*/
	RoutingApi *RoutingApi `yaml:"-"`

	/*MetronEndpoint - Descr: The port used to emit legacy messages to the Metron agent. Default: 3456
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

}