package nats_stream_forwarder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NatsStreamForwarderJob struct {

	/*Nats - Descr: NATS addresses Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}