package register_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cf struct {

	/*AdminPassword - Descr: Password of the CF admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*AdminUser - Descr: Username of the CF admin user Default: <nil>
*/
	AdminUser interface{} `yaml:"admin_user,omitempty"`

}