package register_service_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*AdminClientSecret - Descr: Client Secret of the UAA admin client Default: <nil>
*/
	AdminClientSecret interface{} `yaml:"admin_client_secret,omitempty"`

	/*AdminClientId - Descr: Client ID of the UAA admin client Default: <nil>
*/
	AdminClientId interface{} `yaml:"admin_client_id,omitempty"`

	/*ClientId - Descr: The client id generated by the Cloud Controller on behalf of the service broker Default: p-spring-cloud-services
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

}