package bootstrap 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BootstrapJob struct {

	/*ClusterIps - Descr: IP addresses of all MySQL nodes Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*DatabaseStartupTimeout - Descr: Maximum time to transition to or from a stopped or started state before we timeout. Default: <nil>
*/
	DatabaseStartupTimeout interface{} `yaml:"database_startup_timeout,omitempty"`

	/*BootstrapEndpoint - Descr: Password used to contact the bootstrap endpoints via Basic Auth Default: <nil>
*/
	BootstrapEndpoint *BootstrapEndpoint `yaml:"bootstrap_endpoint,omitempty"`

	/*HealthcheckPort - Descr: Port used by healthcheck process to listen on Default: 9200
*/
	HealthcheckPort interface{} `yaml:"healthcheck_port,omitempty"`

}