package bootstrap 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BootstrapEndpoint struct {

	/*Password - Descr: Password used to contact the bootstrap endpoints via Basic Auth Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Username - Descr: Username used to contact the bootstrap endpoints via Basic Auth Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

}