package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Loggregator struct {

	/*Etcd - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

}