package bootstrap 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BootstrapJob struct {

	/*CfMysql - Descr: Port used by healthcheck process to listen on Default: 9200
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}