package bootstrap 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Port used by healthcheck process to listen on Default: 9200
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

}