package bootstrap 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*ClusterIps - Descr: IP addresses of all MySQL nodes Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*GaleraHealthcheck - Descr: Password used to contact the sidecar endpoints via Basic Auth Default: <nil>
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

	/*HealthcheckPort - Descr: Port used by healthcheck process to listen on Default: 9200
*/
	HealthcheckPort interface{} `yaml:"healthcheck_port,omitempty"`

}