package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServerJob struct {

	/*EtcdMetricsServer - Descr: PEM-encoded client key Default: 
*/
	EtcdMetricsServer *EtcdMetricsServer `yaml:"etcd_metrics_server,omitempty"`

}