package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cf struct {

	/*Nats - Descr: The password to use when authenticating with NATS Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}