package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RabbitmqHaproxy struct {

	/*Stats - Descr: Admin password to access HaProxy stats dashboard Default: <nil>
*/
	Stats *Stats `yaml:"stats,omitempty"`

	/*ServerIps - Descr: List of IP addresses for the RabbitMQ cluster to proxy Default: <nil>
*/
	ServerIps interface{} `yaml:"server_ips,omitempty"`

	/*Ports - Descr: List of ports (as string!) to forward to the RabbitMQ cluster Default: <nil>
*/
	Ports interface{} `yaml:"ports,omitempty"`

}