package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RabbitmqHaproxyJob struct {

	/*RabbitmqHaproxy - Descr: Admin password to access HaProxy stats dashboard Default: <nil>
*/
	RabbitmqHaproxy *RabbitmqHaproxy `yaml:"rabbitmq-haproxy,omitempty"`

	/*RabbitmqBroker - Descr: IP address RabbitMQ management UI requests will be routed to, typically that of RabbitMQ HAproxy VM Default: <nil>
*/
	RabbitmqBroker *RabbitmqBroker `yaml:"rabbitmq-broker,omitempty"`

	/*Cf - Descr: The password to use when authenticating with NATS Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*SyslogAggregator - Descr: Syslog drain hostname Default: <nil>
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

}