package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Rabbitmq struct {

	/*ManagementIp - Descr: IP address RabbitMQ management UI requests will be routed to, typically that of RabbitMQ HAproxy VM Default: <nil>
*/
	ManagementIp interface{} `yaml:"management_ip,omitempty"`

	/*ManagementDomain - Descr: Domain that will be used to access RabbitMQ management UI, typically the system CF/CC domain. Default: <nil>
*/
	ManagementDomain interface{} `yaml:"management_domain,omitempty"`

}