package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RabbitmqBroker struct {

	/*Rabbitmq - Descr: IP address RabbitMQ management UI requests will be routed to, typically that of RabbitMQ HAproxy VM Default: <nil>
*/
	Rabbitmq *Rabbitmq `yaml:"rabbitmq,omitempty"`

	/*RegistrationInterval - Descr: How often the registrar should send messages to the router Default: 20s
*/
	RegistrationInterval interface{} `yaml:"registration_interval,omitempty"`

}