package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Stats struct {

	/*Password - Descr: Admin password to access HaProxy stats dashboard Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Username - Descr: Admin username to access HaProxy stats dashboard Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

}