package rabbitmq_haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SyslogAggregator struct {

	/*Address - Descr: Syslog drain hostname Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Port - Descr: Syslog drain port Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

}