package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Authn struct {

	/*SecurityJarBase64Bits - Descr: base64 encoding of authentication security jar Default: 
*/
	SecurityJarBase64Bits interface{} `yaml:"security_jar_base64_bits,omitempty"`

}