package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ClusterTopology struct {

	/*NumberOfLocators - Descr: Current topology Default: 2
*/
	NumberOfLocators interface{} `yaml:"number_of_locators,omitempty"`

	/*MinNumberOfLocators - Descr: min number of locators which should be present Default: 2
*/
	MinNumberOfLocators interface{} `yaml:"min_number_of_locators,omitempty"`

}