package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ExternalDependencies struct {

	/*Router - Descr: System domain Default: <nil>
*/
	Router *Router `yaml:"router,omitempty"`

}