package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Gemfire struct {

	/*Locator - Descr: RAM allocated to the locator VM in MB Default: <nil>
*/
	Locator *Locator `yaml:"locator,omitempty"`

	/*ClusterTopology - Descr: min number of locators which should be present Default: 2
*/
	ClusterTopology *ClusterTopology `yaml:"cluster_topology,omitempty"`

}