package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Gemfire struct {

	/*Locator - Descr: Port the Locator will listen on for REST API Default: 8080
*/
	Locator *Locator `yaml:"locator,omitempty"`

	/*ClusterTopology - Descr: min number of locators which should be present Default: 2
*/
	ClusterTopology *ClusterTopology `yaml:"cluster_topology,omitempty"`

	/*Authn - Descr: base64 encoding of authentication security jar Default: 
*/
	Authn *Authn `yaml:"authn,omitempty"`

}