package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type LocatorJob struct {

	/*ExternalDependencies - Descr: System domain Default: <nil>
*/
	ExternalDependencies *ExternalDependencies `yaml:"external_dependencies,omitempty"`

	/*Gemfire - Descr: List of GemFire Locator addresses of the form X.X.X.X Default: <nil>
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

}