package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Router struct {

	/*SystemDomain - Descr: System domain Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

}