package rep_windows 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Executor - Descr: Directory to run the healthcheck process from Default: <nil>
*/
	Executor *Executor `yaml:"executor,omitempty"`

	/*Rep - Descr: maximum number of idle http connections Default: <nil>
*/
	Rep *Rep `yaml:"rep,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}