package atc 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaAuth struct {

	/*ClientSecret - Descr: UAA client secret to use for OAuth. Default: 
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

	/*CfApiUrl - Descr: Cloud Foundry api endpoint url. Default: 
*/
	CfApiUrl interface{} `yaml:"cf_api_url,omitempty"`

	/*AuthUrl - Descr: UAA authorization endpoint url to use for OAuth. Default: 
*/
	AuthUrl interface{} `yaml:"auth_url,omitempty"`

	/*TokenUrl - Descr: UAA token endpoint url to use for OAuth. Default: 
*/
	TokenUrl interface{} `yaml:"token_url,omitempty"`

	/*CfSpaces - Descr: List of space GUIDs for Cloud Foundry spaces whose developers
will have access.
 Default: []
*/
	CfSpaces interface{} `yaml:"cf_spaces,omitempty"`

	/*CfCaCert - Descr: Cloud Foundry CA Certificate. Default: 
*/
	CfCaCert interface{} `yaml:"cf_ca_cert,omitempty"`

	/*ClientId - Descr: UAA client ID to use for OAuth. Default: 
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

}