package etcd_test_consumer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdTestConsumerJob struct {

	/*Etcd - Descr: PEM-encoded client key Default: <nil>
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

}