package etcd_test_consumer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Etcd struct {

	/*ServerKey - Descr: PEM-encoded server key Default: <nil>
*/
	ServerKey interface{} `yaml:"server_key,omitempty"`

	/*ClientCert - Descr: PEM-encoded client certificate Default: <nil>
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

	/*ClientKey - Descr: PEM-encoded client key Default: <nil>
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

	/*RequireSsl - Descr: enable ssl for all communication with etcd Default: true
*/
	RequireSsl interface{} `yaml:"require_ssl,omitempty"`

	/*Machines - Descr: Addresses of etcd machines Default: <nil>
*/
	Machines interface{} `yaml:"machines,omitempty"`

	/*CaCert - Descr: PEM-encoded CA certificate Default: <nil>
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

	/*ServerCert - Descr: PEM-encoded server certificate Default: <nil>
*/
	ServerCert interface{} `yaml:"server_cert,omitempty"`

}