package vizzini 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VizziniJob struct {

	/*Vizzini - Descr: default timeout for ginkgo assertions Default: <nil>
*/
	Vizzini *Vizzini `yaml:"vizzini,omitempty"`

}