package vizzini 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Vizzini struct {

	/*Bbs - Descr: The address of the BBS Default: bbs.service.cf.internal:8889
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*Ssh - Descr: Host and port for the SSH proxy Default: ssh-proxy.service.cf.internal:2222
*/
	Ssh *Ssh `yaml:"ssh,omitempty"`

	/*Verbose - Descr: Run tests in verbose mode Default: false
*/
	Verbose interface{} `yaml:"verbose,omitempty"`

	/*EventuallyTimeout - Descr: default timeout for ginkgo assertions Default: <nil>
*/
	EventuallyTimeout interface{} `yaml:"eventually_timeout,omitempty"`

	/*RoutableDomainSuffix - Descr: The deployment's routable domain name Default: <nil>
*/
	RoutableDomainSuffix interface{} `yaml:"routable_domain_suffix,omitempty"`

	/*Nodes - Descr: The number of nodes to run the tests with Default: 4
*/
	Nodes interface{} `yaml:"nodes,omitempty"`

}