package vizzini 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VizziniJob struct {

	/*Vizzini - Descr: The number of nodes to run the tests with Default: 4
*/
	Vizzini *Vizzini `yaml:"vizzini,omitempty"`

}