package vizzini 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VizziniJob struct {

	/*Vizzini - Descr: PEM-encoded client key Default: <nil>
*/
	Vizzini *Vizzini `yaml:"vizzini,omitempty"`

}