package postgres 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PostgresJob struct {

	/*Databases - Descr: A list of database roles and associated properties to create Default: <nil>
*/
	Databases *Databases `yaml:"databases,omitempty"`

}