package postgres 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PostgresJob struct {

	/*Databases - Descr: The database scheme Default: <nil>
*/
	Databases *Databases `yaml:"databases,omitempty"`

}