package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SmokeTestsJob struct {

	/*SmokeTests - Descr: Toggles setup and cleanup of the Elastic Runtime organization Default: false
*/
	SmokeTests *SmokeTests `yaml:"smoke_tests,omitempty"`

}