package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SmokeTestsJob struct {

	/*SmokeTests - Descr: The Elastic Runtime API user Default: <nil>
*/
	SmokeTests *SmokeTests `yaml:"smoke_tests,omitempty"`

}