package blobstore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BlobstoreJob struct {

	/*Domain - Descr: The system domain.  The public server will listen on host 'blobstore.system-domain.tld' Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Blobstore - Descr: The PEM-encoded private key for signing TLS/SSL traffic Default: <nil>
*/
	Blobstore *Blobstore `yaml:"blobstore,omitempty"`

}