package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*AcceptanceTests - Descr: Flag to include the security groups test suite. Default: false
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

}