package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*AcceptanceTests - Descr: Flag for using HTTP when making api and application requests rather than the default HTTPS Default: false
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

}