package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Backend struct {

	/*Hosts - Descr: A list of the IP addresses of each Docker proxy to load-balance Default: []
*/
	Hosts interface{} `yaml:"hosts,omitempty"`

	/*Port - Descr: TCP Port that each backend registry is listening on Default: 5000
*/
	Port interface{} `yaml:"port,omitempty"`

}