package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Docker struct {

	/*Proxy - Descr: PEM-encoded private key for HTTPS proxy operation Default: <nil>
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

}