package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ProxyJob struct {

	/*Docker - Descr: PEM-encoded private key for HTTPS proxy operation Default: <nil>
*/
	Docker *Docker `yaml:"docker,omitempty"`

}