package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Proxy struct {

	/*Backend - Descr: TCP Port that each backend registry is listening on Default: 5000
*/
	Backend *Backend `yaml:"backend,omitempty"`

	/*Ssl - Descr: PEM-encoded private key for HTTPS proxy operation Default: <nil>
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}