package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*Cert - Descr: PEM-encoded SSL certificate for HTTPS proxy operation Default: <nil>
*/
	Cert interface{} `yaml:"cert,omitempty"`

	/*Key - Descr: PEM-encoded private key for HTTPS proxy operation Default: <nil>
*/
	Key interface{} `yaml:"key,omitempty"`

}