package metron_agent_windows 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Loggregator struct {

	/*Etcd - Descr: Number of concurrent requests to ETCD Default: 10
*/
	Etcd *LoggregatorEtcd `yaml:"etcd,omitempty"`

	/*Tls - Descr: CA root required for key/cert verification Default: 
*/
	Tls *LoggregatorTls `yaml:"tls,omitempty"`

}