package nats 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NatsJob struct {

	/*Nats - Descr: The port for the NATS server to listen on. Default: 4222
*/
	Nats *Nats `yaml:"nats,omitempty"`

}