package nfs_mounter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NfsMounterJob struct {

	/*NfsServer - Descr: NFS server for droplets and apps (not used in an AWS deploy, use s3 instead) Default: <nil>
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

}