package arbitrator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ArbitratorJob struct {

	/*CfMysql - Descr: Password for the MySQL server admin user Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}