package arbitrator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*AdminPassword - Descr: Password for the MySQL server admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*Port - Descr: Port the mysql server should bind to Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

	/*GaleraPort - Descr: Port which garbd listens on Default: 4567
*/
	GaleraPort interface{} `yaml:"galera_port,omitempty"`

	/*ClusterIps - Descr: (Optional) List of nodes.  Must have the same number of ips as there are nodes in the cluster Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*GaleraHealthcheck - Descr: Port used by sidecar process to listen on Default: 9200
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

	/*AdminUsername - Descr: Username for the MySQL server admin user Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

}