package verify_cluster_schemas 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Port used to access galera healthcheck Default: 9200
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

	/*Proxy - Descr: IP address of the arbitrator if it exists Default: <nil>
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

}