package verify_cluster_schemas 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Proxy struct {

	/*ArbitratorIp - Descr: IP address of the arbitrator if it exists Default: <nil>
*/
	ArbitratorIp interface{} `yaml:"arbitrator_ip,omitempty"`

}