package verify_cluster_schemas 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VerifyClusterSchemasJob struct {

	/*CfMysql - Descr: Port used to access galera healthcheck Default: 9200
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}