package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*AcceptanceTests - Descr: Flag to inlude whether we check DEA/Diego interoperability Default: false
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

}