package metron_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Loggregator struct {

	/*DropsondeIncomingPort - Descr: Port where loggregator listens for dropsonde log messages Default: 3457
*/
	DropsondeIncomingPort interface{} `yaml:"dropsonde_incoming_port,omitempty"`

	/*Etcd - Descr: Number of concurrent requests to ETCD Default: 10
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*Tls - Descr: CA root required for key/cert verification Default: 
*/
	Tls *LoggregatorTls `yaml:"tls,omitempty"`

}