package metron_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MetronAgent struct {

	/*Debug - Descr: boolean value to turn on verbose mode Default: false
*/
	Debug interface{} `yaml:"debug,omitempty"`

	/*EnableBuffer - Descr: DEPRECATED Default: false
*/
	EnableBuffer interface{} `yaml:"enable_buffer,omitempty"`

	/*Tls - Descr: TLS client certificate Default: 
*/
	Tls *MetronAgentTls `yaml:"tls,omitempty"`

	/*Tcp - Descr: The number of bytes which can be buffered prior to TCP writes (applies to TLS over TCP) Default: 10240
*/
	Tcp *Tcp `yaml:"tcp,omitempty"`

	/*DropsondeIncomingPort - Descr: Incoming port for dropsonde log messages Default: 3457
*/
	DropsondeIncomingPort interface{} `yaml:"dropsonde_incoming_port,omitempty"`

	/*Deployment - Descr: Name of deployment (added as tag on all outgoing metrics) Default: <nil>
*/
	Deployment interface{} `yaml:"deployment,omitempty"`

	/*BufferSize - Descr: DEPRECATED Default: 10000
*/
	BufferSize interface{} `yaml:"buffer_size,omitempty"`

	/*Zone - Descr: Availability zone where this agent is running Default: <nil>
*/
	Zone interface{} `yaml:"zone,omitempty"`

	/*Logrotate - Descr: The frequency in minutes which logrotate will rotate VM logs Default: 5
*/
	Logrotate *Logrotate `yaml:"logrotate,omitempty"`

	/*PreferredProtocol - Descr: Preferred protocol to droppler (udp|tls) Default: udp
*/
	PreferredProtocol interface{} `yaml:"preferred_protocol,omitempty"`

}