package nfs_mounter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NfsMounterJob struct {

	/*NfsServer - Descr: Pipefs directory for NFS idmapd Default: /var/lib/nfs/rpc_pipefs
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

}