package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Metron struct {

	/*Port - Descr: The port used to emit dropsonde messages to the Metron agent. Default: 3457
*/
	Port interface{} `yaml:"port,omitempty"`

}