package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RoutingApi struct {

	/*AuthDisabled - Descr: When false, Routing API requires OAuth tokens for authentication. Default: false
*/
	AuthDisabled interface{} `yaml:"auth_disabled,omitempty"`

	/*Enabled - Descr: When enabled, GoRouter will fetch HTTP routes from the Routing API in addition to routes obtained via NATS. Default: false
*/
	Enabled interface{} `yaml:"enabled,omitempty"`

	/*Port - Descr: Port on which Routing API is running. Default: 3000
*/
	Port interface{} `yaml:"port,omitempty"`

}