package swarm_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SwarmManagerJob struct {

	/*Env - Descr: HTTPS proxy that Docker should use Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*SwarmManager - Descr: Log level (options: debug, info, warn, error, fatal, panic) Default: info
*/
	SwarmManager *SwarmManager `yaml:"swarm_manager,omitempty"`

	/*Swarm - Descr: Swarm discovery options Default: []
*/
	Swarm *Swarm `yaml:"swarm,omitempty"`

	/*Docker - Descr: TLS certificate file Default: <nil>
*/
	Docker *Docker `yaml:"docker,omitempty"`

}