package verify_cluster_schemas 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GaleraHealthcheck struct {

	/*Port - Descr: Port used by sidecar process to listen on Default: 9200
*/
	Port interface{} `yaml:"port,omitempty"`

	/*EndpointUsername - Descr: Username used to authenticate with galera healthcheck Default: <nil>
*/
	EndpointUsername interface{} `yaml:"endpoint_username,omitempty"`

	/*EndpointPassword - Descr: Password used to authenticate with galera healthcheck Default: <nil>
*/
	EndpointPassword interface{} `yaml:"endpoint_password,omitempty"`

}