package verify_cluster_schemas 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VerifyClusterSchemasJob struct {

	/*CfMysql - Descr: IP address of the arbitrator if it exists Default: 
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*ClusterIps - Descr: IP addresses of all MySQL nodes Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*Port - Descr: Port the mysql servers are running on Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

	/*AdminUsername - Descr: Username for the MySQL server admin user Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*AdminPassword - Descr: Password for the MySQL server admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

}