package cloud_controller_clock 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PendingDroplets struct {

	/*FrequencyInSeconds - Descr: How often the droplet pending cleanup job runs Default: 300
*/
	FrequencyInSeconds interface{} `yaml:"frequency_in_seconds,omitempty"`

}