package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Rep struct {

	/*ListenAddr - Descr: address to serve auction and LRP stop requests on Default: 0.0.0.0:1800
*/
	ListenAddr interface{} `yaml:"listen_addr,omitempty"`

	/*Zone - Descr: The zone associated with the rep Default: <nil>
*/
	Zone interface{} `yaml:"zone,omitempty"`

	/*TrustedCerts - Descr: Concatenation of trusted CA certificates to be made available inside the rootfses Default: <nil>
*/
	TrustedCerts interface{} `yaml:"trusted_certs,omitempty"`

	/*EvacuationPollingIntervalInSeconds - Descr: The interval to look for completed tasks and LRPs during evacuation in seconds Default: 10
*/
	EvacuationPollingIntervalInSeconds interface{} `yaml:"evacuation_polling_interval_in_seconds,omitempty"`

	/*DropsondePort - Descr: local metron agent's port Default: 3457
*/
	DropsondePort interface{} `yaml:"dropsonde_port,omitempty"`

	/*Bbs - Descr: PEM-encoded client key Default: <nil>
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*PollingIntervalInSeconds - Descr: The interval to look for completed tasks and LRPs in seconds Default: 30
*/
	PollingIntervalInSeconds interface{} `yaml:"polling_interval_in_seconds,omitempty"`

	/*OptionalPlacementTags - Descr: Array of optional tags used for scheduling Tasks and LRPs Default: []
*/
	OptionalPlacementTags interface{} `yaml:"optional_placement_tags,omitempty"`

	/*RootfsProviders - Descr: Array of schemes for which the underlying garden can support arbitrary root filesystems Default: [docker]
*/
	RootfsProviders interface{} `yaml:"rootfs_providers,omitempty"`

	/*PreloadedRootfses - Descr: Array of name:absolute_path pairs representing root filesystems preloaded onto the underlying garden Default: <nil>
*/
	PreloadedRootfses interface{} `yaml:"preloaded_rootfses,omitempty"`

	/*EvacuationTimeoutInSeconds - Descr: The time to wait for evacuation to complete in seconds Default: 600
*/
	EvacuationTimeoutInSeconds interface{} `yaml:"evacuation_timeout_in_seconds,omitempty"`

	/*UseAzureFaultDomains - Descr: Use Azure Fault-Domains to determine the value of the zone. The value of the zone will be z<FD-index>. e.g. z0, z1, etc. Default: false
*/
	UseAzureFaultDomains interface{} `yaml:"use_azure_fault_domains,omitempty"`

	/*PlacementTags - Descr: Array of tags used for scheduling Tasks and LRPs Default: []
*/
	PlacementTags interface{} `yaml:"placement_tags,omitempty"`

	/*LogLevel - Descr: Log level Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*DebugAddr - Descr: address at which to serve debug info Default: 127.0.0.1:17008
*/
	DebugAddr interface{} `yaml:"debug_addr,omitempty"`

}