package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Volman struct {

	/*DriverPaths - Descr: Experimental: OS style path string containing the directories volman will look in for voldriver specs (delimited by : or ; depending on the OS) Default: /var/vcap/data/voldrivers
*/
	DriverPaths interface{} `yaml:"driver_paths,omitempty"`

}