package statsd_injector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StatsdInjectorJob struct {

	/*StatsdInjector - Descr: The port on which metron is running Default: 3457
*/
	StatsdInjector *StatsdInjector `yaml:"statsd_injector,omitempty"`

}