package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AuctioneerJob struct {

	/*Diego - Descr: address at which to serve debug info Default: 127.0.0.1:17001
*/
	Diego *Diego `yaml:"diego,omitempty"`

}