package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Auctioneer - Descr: address at which to serve debug info Default: 127.0.0.1:17001
*/
	Auctioneer *Auctioneer `yaml:"auctioneer,omitempty"`

}