package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cf struct {

	/*AdminPassword - Descr: Password of the admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*ApiUrl - Descr: Full URL of Cloud Foundry API Default: <nil>
*/
	ApiUrl interface{} `yaml:"api_url,omitempty"`

	/*SystemDomain - Descr: Cloud Foundry system domain, used for the Console application's URL Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*ConsoleSubdomain - Descr: Console subdomain name Default: apps
*/
	ConsoleSubdomain interface{} `yaml:"console_subdomain,omitempty"`

	/*AdminUsername - Descr: Username of the admin user Default: <nil>
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*MaximumHealthCheckTimeout - Descr: The maximum time (in seconds) for cf-push to wait for console app to start Default: 600
*/
	MaximumHealthCheckTimeout interface{} `yaml:"maximum_health_check_timeout,omitempty"`

}