package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Console struct {

	/*Password - Descr: Password credential for database for Console application Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Adapter - Descr: adapter type (mysql or postgresql) of database server for Console application Default: postgresql
*/
	Adapter interface{} `yaml:"adapter,omitempty"`

	/*Username - Descr: Username credential for database for Console application Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Ip - Descr: IP of database server for Console application Default: <nil>
*/
	Ip interface{} `yaml:"ip,omitempty"`

	/*Port - Descr: Port of database server for Console application Default: 2544
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Name - Descr: Postgres database name for Console application Default: console
*/
	Name interface{} `yaml:"name,omitempty"`

}