package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Env struct {

	/*SecretToken - Descr: Secret token for signing cookies Default: <nil>
*/
	SecretToken interface{} `yaml:"secret_token,omitempty"`

	/*CfLoggregatorHttpUrl - Descr: Full URL of Loggregator's HTTP API Default: <nil>
*/
	CfLoggregatorHttpUrl interface{} `yaml:"cf_loggregator_http_url,omitempty"`

	/*GenericWhiteLabelConfigJson - Descr: White labeling for company name Default: Pivotal
*/
	GenericWhiteLabelConfigJson *GenericWhiteLabelConfigJson `yaml:"generic_white_label_config_json,omitempty"`

	/*CfNotificationsServiceUrl - Descr: Full URL of Notifications Service's HTTP API Default: <nil>
*/
	CfNotificationsServiceUrl interface{} `yaml:"cf_notifications_service_url,omitempty"`

	/*RailsEnv - Descr: Rails environment Default: production
*/
	RailsEnv interface{} `yaml:"rails_env,omitempty"`

	/*CfConsoleUrl - Descr: Full URL of Console application Default: <nil>
*/
	CfConsoleUrl interface{} `yaml:"cf_console_url,omitempty"`

	/*EnableNonAdminRoleManagement - Descr: Allow non-admins to manage users in the Console application Default: false
*/
	EnableNonAdminRoleManagement interface{} `yaml:"enable_non_admin_role_management,omitempty"`

	/*SystemOrgQuotaName - Descr: The name of the quota to be assigned to the system org Default: runaway
*/
	SystemOrgQuotaName interface{} `yaml:"system_org_quota_name,omitempty"`

	/*RackEnv - Descr: Rack environment Default: production
*/
	RackEnv interface{} `yaml:"rack_env,omitempty"`

	/*AppsManagerConfigJson - Descr: White labeling for product name Default: Apps Manager
*/
	AppsManagerConfigJson *AppsManagerConfigJson `yaml:"apps_manager_config_json,omitempty"`

	/*CfCcApiUrl - Descr: Full URL of Cloud Foundry API Default: <nil>
*/
	CfCcApiUrl interface{} `yaml:"cf_cc_api_url,omitempty"`

	/*DefaultFrom - Descr: Default 'from' address for e-mails generated by Console application Default: <nil>
*/
	DefaultFrom interface{} `yaml:"default_from,omitempty"`

	/*EnableInternalUserStore - Descr: Enable internal user store in the Console application Default: false
*/
	EnableInternalUserStore interface{} `yaml:"enable_internal_user_store,omitempty"`

	/*DefaultReplyTo - Descr: Default 'reply-to' address for e-mails generated by Console application Default: <nil>
*/
	DefaultReplyTo interface{} `yaml:"default_reply_to,omitempty"`

	/*UsageServiceHost - Descr: The host for the usage service Default: <nil>
*/
	UsageServiceHost interface{} `yaml:"usage_service_host,omitempty"`

	/*BundleWithout - Descr:  Default: test:development
*/
	BundleWithout interface{} `yaml:"bundle_without,omitempty"`

}