package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*HttpsOnlyMode - Descr: When rendering app route urls, prefix all of them with https Default: false
*/
	HttpsOnlyMode interface{} `yaml:"https_only_mode,omitempty"`

	/*SkipCertVerify - Descr: when connecting over TLS, don't verify certificates Default: false
*/
	SkipCertVerify interface{} `yaml:"skip_cert_verify,omitempty"`

}