package broker_registrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerRegistrarJob struct {

	/*Cf - Descr: Username of the admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*CfMysql - Descr: Basic Auth password for the service broker Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}