package service_backup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Azure struct {

	/*StorageAccount - Descr: Azure account name to access the storage service Default: <nil>
*/
	StorageAccount interface{} `yaml:"storage_account,omitempty"`

	/*Container - Descr: Container to which backups are uploaded Default: <nil>
*/
	Container interface{} `yaml:"container,omitempty"`

	/*BlobStoreBaseUrl - Descr: Path in url to which backups are uploaded Default: core.windows.net
*/
	BlobStoreBaseUrl interface{} `yaml:"blob_store_base_url,omitempty"`

	/*StorageAccessKey - Descr: Azure access key to access the storage service Default: <nil>
*/
	StorageAccessKey interface{} `yaml:"storage_access_key,omitempty"`

	/*Path - Descr: Path in container to which backups are uploaded Default: <nil>
*/
	Path interface{} `yaml:"path,omitempty"`

}