package service_backup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Destination struct {

	/*S3 - Descr: Bucket to which backups are uploaded Default: <nil>
*/
	S3 *S3 `yaml:"s3,omitempty"`

	/*Scp - Descr: SSH port on remote server Default: 22
*/
	Scp *Scp `yaml:"scp,omitempty"`

	/*Azure - Descr: Path in container to which backups are uploaded Default: <nil>
*/
	Azure *Azure `yaml:"azure,omitempty"`

}