package service_backup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Scp struct {

	/*Key - Descr: SSH key identity file for remote server Default: <nil>
*/
	Key interface{} `yaml:"key,omitempty"`

	/*User - Descr: SCP user on remote server Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Server - Descr: SCP remote server host Default: <nil>
*/
	Server interface{} `yaml:"server,omitempty"`

	/*Destination - Descr: Remote path on server for upload Default: <nil>
*/
	Destination interface{} `yaml:"destination,omitempty"`

	/*Port - Descr: SSH port on remote server Default: 22
*/
	Port interface{} `yaml:"port,omitempty"`

}