package service_backup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ServiceBackupJob struct {

	/*ServiceBackup - Descr: Schedule on which to perform backups. Supports "* * * * *" syntax. Default: <nil>
*/
	ServiceBackup *ServiceBackup `yaml:"service-backup,omitempty"`

}