package test_notifications_ui 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*AdminClient - Descr: UAA Admin client ID Default: <nil>
*/
	AdminClient interface{} `yaml:"admin_client,omitempty"`

	/*AdminSecret - Descr: UAA Admin client secret Default: <nil>
*/
	AdminSecret interface{} `yaml:"admin_secret,omitempty"`

}