package swarm_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Docker struct {

	/*TcpPort - Descr: TCP port where Docker daemon will listen to (if not set, TCP will not be available) Default: 4243
*/
	TcpPort interface{} `yaml:"tcp_port,omitempty"`

}