package swarm_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SwarmAgent struct {

	/*Advertise - Descr: Address of the Docker Engine joining the cluster. Swarm manager(s) MUST be able to reach the Docker Engine at this address. Default: <nil>
*/
	Advertise interface{} `yaml:"advertise,omitempty"`

	/*Ttl - Descr: Sets the expiration of an ephemeral node Default: 60s
*/
	Ttl interface{} `yaml:"ttl,omitempty"`

	/*Heartbeat - Descr: Time in second between each heartbeat Default: 20s
*/
	Heartbeat interface{} `yaml:"heartbeat,omitempty"`

	/*Debug - Descr: Enable debug mode Default: false
*/
	Debug interface{} `yaml:"debug,omitempty"`

	/*LogLevel - Descr: Log level (options: debug, info, warn, error, fatal, panic) Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

}