package cflinuxfs2_smoke_test 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cflinuxfs2SmokeTestJob struct {

	/*Cflinuxfs2Rootfs - Descr: certficates to add to the rootfs trust store Default: <nil>
*/
	Cflinuxfs2Rootfs *Cflinuxfs2Rootfs `yaml:"cflinuxfs2-rootfs,omitempty"`

}