package test_restore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Database port for contacting mysql Default: 3306
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

}