package test_restore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Destination struct {

	/*S3 - Descr: AWS Secret Access Key to access the blobstore Default: <nil>
*/
	S3 *S3 `yaml:"s3,omitempty"`

}