package test_restore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type S3 struct {

	/*BucketPath - Descr: Path in bucket to which backups are uploaded Default: <nil>
*/
	BucketPath interface{} `yaml:"bucket_path,omitempty"`

	/*BucketName - Descr: Bucket to which backups are uploaded Default: <nil>
*/
	BucketName interface{} `yaml:"bucket_name,omitempty"`

	/*AccessKeyId - Descr: AWS Access Key to access the blobstore Default: <nil>
*/
	AccessKeyId interface{} `yaml:"access_key_id,omitempty"`

	/*SecretAccessKey - Descr: AWS Secret Access Key to access the blobstore Default: <nil>
*/
	SecretAccessKey interface{} `yaml:"secret_access_key,omitempty"`

	/*EndpointUrl - Descr: S3 endpoint Default: https://s3.amazonaws.com
*/
	EndpointUrl interface{} `yaml:"endpoint_url,omitempty"`

}