package test_restore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestRestoreJob struct {

	/*CfMysql - Descr: Database port for contacting mysql Default: 3306
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*ServiceBackup - Descr: AWS Secret Access Key to access the blobstore Default: <nil>
*/
	ServiceBackup *ServiceBackup `yaml:"service-backup,omitempty"`

	/*CfMysqlBackup - Descr: Symmetric key to decrypt backups Default: <nil>
*/
	CfMysqlBackup *CfMysqlBackup `yaml:"cf-mysql-backup,omitempty"`

}