package test_restore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestRestore struct {

	/*TestDb - Descr: Name of test database to create. Note: do not name this "test" Default: mysql_backup_test
*/
	TestDb interface{} `yaml:"test_db,omitempty"`

	/*WaitTimeForBackup - Descr: How long the errand will wait for the backup to get streamed to destination, in seconds Default: 400
*/
	WaitTimeForBackup interface{} `yaml:"wait_time_for_backup,omitempty"`

}