package nsync 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NsyncJob struct {

	/*Diego - Descr: PEM-encoded client certificate Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}