package nsync 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NsyncJob struct {

	/*Diego - Descr: address at which to serve debug info Default: 0.0.0.0:17007
*/
	Diego *Diego `yaml:"diego,omitempty"`

}