package converger 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConvergerJob struct {

	/*Diego - Descr: the interval, in seconds, between kicks to tasks in seconds Default: 30
*/
	Diego *Diego `yaml:"diego,omitempty"`

}