package converger 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Converger - Descr: the interval, in seconds, between kicks to tasks in seconds Default: 30
*/
	Converger *Converger `yaml:"converger,omitempty"`

}