package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Rep - Descr: maximum number of idle http connections Default: <nil>
*/
	Rep *Rep `yaml:"rep,omitempty"`

	/*Executor - Descr: Concatenation of trusted CA certificates to be used when downloading assets. Default: <nil>
*/
	Executor *Executor `yaml:"executor,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}