package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Rep - Descr: The zone associated with the rep Default: <nil>
*/
	Rep *Rep `yaml:"rep,omitempty"`

	/*Executor - Descr: the inode limit enforced on each garden container. Default: 200000
*/
	Executor *Executor `yaml:"executor,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}