package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RepJob struct {

	/*Diego - Descr: maximum number of idle http connections Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}