package test_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Tests struct {

	/*Performance - Descr: Toggle for running the performance tests Default: <nil>
*/
	Performance interface{} `yaml:"performance,omitempty"`

}