package test_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*AdminClientSecret - Descr: UAA Admin client secret Default: <nil>
*/
	AdminClientSecret interface{} `yaml:"admin_client_secret,omitempty"`

	/*AdminClientId - Descr: UAA Admin client ID Default: <nil>
*/
	AdminClientId interface{} `yaml:"admin_client_id,omitempty"`

}