package streaming_mysql_backup_tool 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BackupServer struct {

	/*Port - Descr: Port number used for listening for backup requests Default: 8081
*/
	Port interface{} `yaml:"port,omitempty"`

}