package streaming_mysql_backup_tool 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Password for the MySQL server admin user Default: <nil>
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

}