package streaming_mysql_backup_tool 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*AdminUsername - Descr: Username for the MySQL server admin user Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*AdminPassword - Descr: Password for the MySQL server admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

}