package streaming_mysql_backup_tool 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StreamingMysqlBackupToolJob struct {

	/*CfMysqlBackup - Descr: Port number used for listening for backup requests Default: 8081
*/
	CfMysqlBackup *CfMysqlBackup `yaml:"cf-mysql-backup,omitempty"`

	/*CfMysql - Descr: Password for the MySQL server admin user Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}