package doppler 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DopplerJob struct {

	/*DopplerEndpoint - Descr: Shared secret used to verify cryptographically signed dropsonde messages Default: <nil>
*/
	DopplerEndpoint *DopplerEndpoint `yaml:"doppler_endpoint,omitempty"`

	/*Doppler - Descr: Zone of the doppler server Default: <nil>
*/
	Doppler *Doppler `yaml:"doppler,omitempty"`

	/*MetronEndpoint - Descr: The port used to emit dropsonde messages to the Metron agent Default: 3457
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*Loggregator - Descr: CA root required for key/cert verification Default: 
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

}