package doppler 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DopplerJob struct {

	/*Doppler - Descr: Number of parallel unmarshallers to run within Doppler Default: 5
*/
	Doppler *Doppler `yaml:"doppler,omitempty"`

	/*MetronEndpoint - Descr: The host used to emit messages to the Metron agent Default: 127.0.0.1
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*Loggregator - Descr: CA root required for key/cert verification Default: 
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*DopplerEndpoint - Descr: Shared secret used to verify cryptographically signed dropsonde messages Default: <nil>
*/
	DopplerEndpoint *DopplerEndpoint `yaml:"doppler_endpoint,omitempty"`

}