package doppler 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Loggregator struct {

	/*Etcd - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*Tls - Descr: CA root required for key/cert verification Default: 
*/
	Tls *LoggregatorTls `yaml:"tls,omitempty"`

}