package canary 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CanaryJob struct {

	/*Diego - Descr: Toggles cli verification of the Elastic Runtime API SSL certificate Default: false
*/
	Diego *Diego `yaml:"diego,omitempty"`

}