package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Services - Descr: Array of services. Note - the broker-deregistrar errand only deregisters the first service Default: <nil>
*/
	Services interface{} `yaml:"services,omitempty"`

}