package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BrokerDeregistrarJob struct {

	/*Cf - Descr: Password of the admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*CfMysql - Descr: Array of services. Note - the broker-deregistrar errand only deregisters the first service Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}