package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Broker - Descr: Array of services. Note - the broker-deregistrar errand only deregisters the first service Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

}