package cc_uploader 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CcUploaderJob struct {

	/*Diego - Descr: External Cloud Controller port Default: 9022
*/
	Diego *Diego `yaml:"diego,omitempty"`

}