package cc_uploader 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CcUploaderJob struct {

	/*Diego - Descr: Address of interface on which to serve files Default: 0.0.0.0:9090
*/
	Diego *Diego `yaml:"diego,omitempty"`

}