package collector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CollectorJob struct {

	/*Collector - Descr: the interval in seconds that varz is checked Default: 30
*/
	Collector *Collector `yaml:"collector,omitempty"`

	/*Nats - Descr: IP of each NATS cluster member. Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}