package collector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CollectorJob struct {

	/*Collector - Descr: name for this bosh deployment. All metrics will be tagged with deployment:XXX when sending them to CloudWatch, Datadog and Graphite Default: <nil>
*/
	Collector *Collector `yaml:"collector,omitempty"`

	/*Nats - Descr: NATS password Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}