package nfs_mounter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NfsMounterJob struct {

	/*NfsServer - Descr: bool to use NFS4 Default: <nil>
*/
	NfsServer *NfsServer `yaml:"nfs_server,omitempty"`

}