package nfs_mounter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type NfsServer struct {

	/*IdmapdDomain - Descr: Domain name for NFS idmapd Default: localdomain
*/
	IdmapdDomain interface{} `yaml:"idmapd_domain,omitempty"`

	/*PipefsDirectory - Descr: Pipefs directory for NFS idmapd Default: /var/lib/nfs/rpc_pipefs
*/
	PipefsDirectory interface{} `yaml:"pipefs_directory,omitempty"`

	/*SharePath - Descr: Location to mount the nfs share Default: /var/vcap/nfs
*/
	SharePath interface{} `yaml:"share_path,omitempty"`

	/*Address - Descr: NFS server for droplets and apps Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Share - Descr: Path to share from the remote NFS server Default: <nil>
*/
	Share interface{} `yaml:"share,omitempty"`

	/*Nfsv4 - Descr: bool to use NFS4 Default: <nil>
*/
	Nfsv4 interface{} `yaml:"nfsv4,omitempty"`

}