package containers 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ContainersJob struct {

	/*Containers - Descr: Containers Array (see below for details) Default: <nil>
*/
	Containers interface{} `yaml:"containers,omitempty"`

}