package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Services - Descr: Array of services, each service contains the list of plans the broker of that service provides Default: <nil>
*/
	Services interface{} `yaml:"services,omitempty"`

	/*Port - Descr: Port for broker Default: 8081
*/
	Port interface{} `yaml:"port,omitempty"`

	/*DbPassword - Descr: The password for the cf-mysql-broker MySQL user Default: <nil>
*/
	DbPassword interface{} `yaml:"db_password,omitempty"`

	/*CookieSecret - Descr: A unique secret key, used to sign sessions Default: <nil>
*/
	CookieSecret interface{} `yaml:"cookie_secret,omitempty"`

	/*DisableQuotaEnforcer - Descr: Disable the Quota Enforcer process Default: false
*/
	DisableQuotaEnforcer interface{} `yaml:"disable_quota_enforcer,omitempty"`

	/*QuotaEnforcer - Descr: The password for the quota-enforcer user Default: <nil>
*/
	QuotaEnforcer *QuotaEnforcer `yaml:"quota_enforcer,omitempty"`

	/*AuthUsername - Descr: Broker's basic auth username Default: <nil>
*/
	AuthUsername interface{} `yaml:"auth_username,omitempty"`

	/*SslEnabled - Descr: Determines use of https in dashboard url and in callback uri for calls to UAA Default: true
*/
	SslEnabled interface{} `yaml:"ssl_enabled,omitempty"`

	/*AuthPassword - Descr: Broker's basic auth password Default: <nil>
*/
	AuthPassword interface{} `yaml:"auth_password,omitempty"`

	/*MaxUserConnectionsDefault - Descr: number of user connections to allow in a plan if not specified Default: 40
*/
	MaxUserConnectionsDefault interface{} `yaml:"max_user_connections_default,omitempty"`

	/*Host - Descr: Optional, The ip to be registered with the cf router for the broker. Defaults to the ip of the vm Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

}