package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type QuotaEnforcer struct {

	/*Pause - Descr: In seconds, the interval that the Quota Enforcer pauses between checks for violators and reformers Default: 1
*/
	Pause interface{} `yaml:"pause,omitempty"`

	/*Password - Descr: The password for the quota-enforcer user Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*IgnoredUsers - Descr: Array of users that the quota enforcer will not enforce quotas on Default: []
*/
	IgnoredUsers interface{} `yaml:"ignored_users,omitempty"`

}