package deploy_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Database struct {

	/*Url - Descr: URL pointing to database Default: <nil>
*/
	Url interface{} `yaml:"url,omitempty"`

	/*MaxOpenConnections - Descr: Maximum number of open connections to the database Default: <nil>
*/
	MaxOpenConnections interface{} `yaml:"max_open_connections,omitempty"`

}