package deploy_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Smtp struct {

	/*Host - Descr: SMTP Host name Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*AuthMechanism - Descr: SMTP Authentication mechanism, should be one of [none plain cram-md5] Default: <nil>
*/
	AuthMechanism interface{} `yaml:"auth_mechanism,omitempty"`

	/*Pass - Descr: Password of the SMTP user Default: <nil>
*/
	Pass interface{} `yaml:"pass,omitempty"`

	/*Port - Descr: SMTP port number Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*User - Descr: Username for the SMTP host Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Crammd5Secret - Descr: Secret to use with CRAMMD5 auth mechanism Default: <nil>
*/
	Crammd5Secret interface{} `yaml:"crammd5_secret,omitempty"`

	/*Tls - Descr: Uses SMTP TLS Default: <nil>
*/
	Tls interface{} `yaml:"tls,omitempty"`

}