package deploy_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*SkipCertVerify - Descr: Whether to verify SSL certs when making HTTP and SMTP requests Default: <nil>
*/
	SkipCertVerify interface{} `yaml:"skip_cert_verify,omitempty"`

}